---
# Sync local backups to Backblaze B2 offsite storage.
# Runs on localhost (controller) — no remote hosts needed.
# Uses rclone sync for efficient, batched transfers.
# Sends Discord notification + logs to MariaDB.
#
# Prerequisites:
#   - rclone installed on controller (apt install rclone)
#   - B2 bucket created with lifecycle rule (see future/BACKBLAZE_B2_OFFSITE_BACKUP.md)
#   - Vault keys set: b2_account_id, b2_application_key, b2_bucket_name
#
# Usage:
#   ansible-playbook backup_offsite.yaml
#   ansible-playbook backup_offsite.yaml -e dry_run=yes    # preview only (--dry-run)
#   ansible-playbook backup_offsite.yaml -e bwlimit=10M    # throttle bandwidth

- name: Sync backups to Backblaze B2 offsite storage
  hosts: localhost
  gather_facts: true
  gather_subset: ['!all', 'date_time']
  vars_files:
    - vars/secrets.yaml
    - vars/semaphore_check.yaml
  vars:
    backup_name: "B2"
    backup_subtype: "Offsite"

  pre_tasks:
    - name: Run standard pre-flight assertions for backup_offsite
      include_tasks: tasks/pre_task_assertions.yaml
      vars:
        pre_playbook: "backup_offsite.yaml"
        pre_hostname: "{{ controller_fqdn }}"

    - name: Assert rclone is installed
      ansible.builtin.command: rclone version
      changed_when: false

    - name: Assert B2 credentials are configured in vault
      ansible.builtin.assert:
        that:
          - b2_account_id is defined and b2_account_id | length > 0
          - b2_application_key is defined and b2_application_key | length > 0
          - b2_bucket_name is defined and b2_bucket_name | length > 0
        fail_msg: "B2 credentials missing from vault — set b2_account_id, b2_application_key, b2_bucket_name"

    - name: Assert backup source directory exists
      ansible.builtin.stat:
        path: "{{ backup_base_dir }}"
      register: _backup_dir
      failed_when: not _backup_dir.stat.exists

  tasks:
    - name: Initialize offsite sync state
      ansible.builtin.set_fact:
        sync_failed: false
        _sync_start: "{{ ansible_date_time.epoch }}"

    - block:
        - name: Sync backups to B2 via rclone
          ansible.builtin.command: >-
            rclone sync
            {{ backup_base_dir }}
            :b2:{{ b2_bucket_name }}
            --transfers {{ b2_transfers | default(4) }}
            --checkers {{ b2_checkers | default(8) }}
            --retries 3
            --low-level-retries 10
            --stats-one-line
            --stats 0
            --log-level NOTICE
            {{ '--bwlimit ' ~ bwlimit if bwlimit is defined else '' }}
            {{ '--dry-run' if dry_run | default(false) | bool else '' }}
          environment:
            RCLONE_B2_ACCOUNT: "{{ b2_account_id }}"
            RCLONE_B2_KEY: "{{ b2_application_key }}"
          register: _rclone_result
          changed_when: _rclone_result.rc == 0
          timeout: 7200
          no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"

      rescue:
        - name: Set sync failed flag
          ansible.builtin.set_fact:
            sync_failed: true

      always:
        - name: Calculate sync duration
          ansible.builtin.set_fact:
            _sync_duration: "{{ now(utc=true).strftime('%s') | int - (_sync_start | int) }}"

        - name: Send offsite sync Discord notification
          include_tasks: tasks/notify.yaml
          vars:
            discord_name: "{{ backup_name }}"
            discord_operation: "Sync"
            discord_author: "{{ controller_fqdn }}"
            discord_status: "{{ 'failed' if sync_failed else 'successful' }}"
            discord_color: "{{ discord_color_failure if sync_failed else discord_color_success }}"
            discord_url: "https://secure.backblaze.com/b2_buckets.htm"
            discord_fields:
              - name: "Bucket"
                value: "{{ b2_bucket_name }}"
              - name: "Duration"
                value: "{{ (_sync_duration | int // 60) }}m {{ (_sync_duration | int % 60) }}s"
              - name: "Dry Run"
                value: "{{ dry_run | default(false) | bool }}"
                inline: true

        - name: Log offsite sync to MariaDB
          include_tasks: tasks/log_mariadb.yaml
          vars:
            log_table: backups
            log_application: "{{ backup_name }}"
            log_hostname: "{{ controller_fqdn }}"
            log_file_name: "{{ ('FAILED_' if sync_failed else '') }}offsite_b2_{{ ansible_date_time.date }}"
            log_file_size: "0"
            log_backup_level: "offline"
