---
# Back up databases from remote Docker containers.
# PostgreSQL/MariaDB: SQL dump piped through gzip. InfluxDB: portable backup → tar.gz.
# Sends Discord notification and logs result to MariaDB.
#
# Usage:
#   ansible-playbook backup_databases.yaml -e hosts_variable=db_primary_postgres
#   ansible-playbook backup_databases.yaml -e hosts_variable=db_primary_influxdb

- name: Back up databases from Docker containers
  hosts: "{{ hosts_variable }}"
  gather_facts: true
  gather_subset: ['!all', 'date_time']
  vars_files:
    - vars/secrets.yaml
    - vars/{{ config_file }}.yaml
  vars:
    config_file: "{{ hosts_variable }}"

  pre_tasks:
    - name: Assert config_file is defined and non-empty
      include_tasks: tasks/assert_config_file.yaml

    - name: Assert sufficient disk space on remote backup dir
      include_tasks: tasks/assert_disk_space.yaml
      vars:
        assert_disk_path: "{{ backup_tmp_dir }}"
        assert_disk_min_gb: "{{ backup_assert_disk_min_gb | default(2) }}"

    - name: Assert sufficient disk space on controller
      include_tasks: tasks/assert_disk_space.yaml
      vars:
        assert_disk_path: "{{ backup_base_dir }}/{{ inventory_hostname }}"
        assert_disk_min_gb: "{{ controller_assert_disk_min_gb | default(2) }}"
        assert_disk_delegate_to: localhost
        assert_disk_become: false

    - name: Assert MariaDB logging database is reachable
      include_tasks: tasks/assert_db_connectivity.yaml

  tasks:
    - name: Delete temp backup directory
      become: true
      ansible.builtin.file:
        state: absent
        path: "{{ backup_tmp_dir }}"
      tags: [always]

    - name: Create temp backup directory
      become: true
      ansible.builtin.file:
        state: directory
        path: "{{ backup_tmp_dir }}"
      tags: [always]

    - name: Initialize backup state
      ansible.builtin.set_fact:
        combined_results: []
        backup_db_failed: false
      tags: [always]

    - block:
        - name: Back up each database
          include_tasks: tasks/backup_single_db.yaml
          loop: "{{ db_names }}"
          loop_control:
            loop_var: _current_db
          when: not ansible_check_mode
          tags: [always]

      rescue:
        - name: Set database backup failed flag
          ansible.builtin.set_fact:
            backup_db_failed: true

      always:
        - name: Send Discord notification for each DB result
          include_tasks: tasks/notify.yaml
          loop: "{{ combined_results }}"
          loop_control:
            loop_var: db_result
          vars:
            discord_name: "{{ backup_name }}"
            discord_operation: "Backup"
            discord_status: "{{ 'failed' if db_result.backup_rc != 0 else 'successful' }}"
            discord_detail: "{{ db_result.db_name }}"
            discord_color: "{{ discord_color_success if db_result.backup_rc == 0 else discord_color_failure }}"
            discord_url: "{{ backup_url }}"
            discord_fields:
              - name: "Date"
                value: "{{ ansible_date_time.date }}"
              - name: "Backup Size"
                value: "{{ (db_result.file_size / 1024 / 1024) | round(2) }}MB"
          tags: [always]

        - name: Send Discord notification for unhandled block error
          include_tasks: tasks/notify.yaml
          when: backup_db_failed
          vars:
            discord_name: "{{ backup_name }}"
            discord_operation: "Backup"
            discord_status: "failed"
            discord_detail: "check Semaphore logs"
            discord_color: "{{ discord_color_failure }}"
            discord_url: "{{ backup_url }}"
          tags: [always]

        - name: Log DB backup results to MariaDB
          include_tasks: tasks/log_mariadb.yaml
          loop: "{{ combined_results }}"
          loop_control:
            loop_var: db_result
          vars:
            log_table: backups
            log_application: "{{ db_result.db_name }}-db"
            log_hostname: "{{ inventory_hostname }}"
            log_file_name: "{{ ('FAILED_' if db_result.backup_rc != 0 else 'backup_') + db_result.db_name + '_' + ansible_date_time.date + '.' + (backup_ext | default('sql')) }}"
            log_file_size: "{{ (db_result.file_size / 1024 / 1024) | round(2) if db_result.backup_rc == 0 else 0 }}"
            log_backup_level: "db"
          tags: [always]
