---
# Back up databases from remote Docker containers.
# PostgreSQL/MariaDB: SQL dump piped through gzip. InfluxDB: portable backup → tar.gz.
# Sends notification and logs result to MariaDB.
#
# Usage:
#   ansible-playbook backup_databases.yaml -e hosts_variable=db_primary_postgres
#   ansible-playbook backup_databases.yaml -e hosts_variable=db_primary_influxdb

- name: Resolve database target host
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
    - "vars/{{ hosts_variable }}.yaml"
  tasks:
    - name: Assert hosts_variable is not both a DB config and inventory group
      ansible.builtin.assert:
        that: groups[hosts_variable] | default([]) | length == 0
        fail_msg: "hosts_variable '{{ hosts_variable }}' collides with an existing inventory group"
      when: db_host is defined

    - name: Add resolved DB host to in-memory inventory
      ansible.builtin.add_host:
        name: "{{ db_host }}"
        groups: "{{ hosts_variable }}"
      when: db_host is defined
      changed_when: false

- name: Back up databases from Docker containers
  hosts: "{{ hosts_variable }}"
  gather_facts: true
  gather_subset: ['!all', 'date_time']
  vars_files:
    - vars/secrets.yaml
    - vars/{{ config_file }}.yaml
  vars:
    config_file: "{{ hosts_variable }}"

  pre_tasks:
    - name: Assert sufficient disk space on remote backup dir
      include_tasks: tasks/assert_disk_space.yaml
      vars:
        assert_disk_path: "{{ backup_tmp_dir }}"
        assert_disk_min_gb: "{{ backup_assert_disk_min_gb | default(2) }}"

    - name: Assert sufficient disk space on controller
      include_tasks: tasks/assert_disk_space.yaml
      vars:
        assert_disk_path: "{{ backup_base_dir }}/{{ backup_stack | default(inventory_hostname) }}"
        assert_disk_min_gb: "{{ controller_assert_disk_min_gb | default(2) }}"
        assert_disk_delegate_to: localhost
        assert_disk_become: false

    - name: Run standard pre-flight assertions
      include_tasks: tasks/pre_task_assertions.yaml
      vars:
        pre_assert_config_file: true
        pre_playbook: "backup_databases.yaml"

  tasks:
    - name: Set run-scoped temp directory (concurrency-safe)
      ansible.builtin.set_fact:
        backup_tmp_dir: "{{ backup_tmp_dir }}/run_{{ ansible_date_time.iso8601_basic_short }}"

    - name: Create run-scoped temp directory
      become: true
      ansible.builtin.file:
        state: directory
        path: "{{ backup_tmp_dir }}"

    - name: Initialize backup state
      ansible.builtin.set_fact:
        combined_results: []
        backup_db_failed: false

    - block:
        - name: Back up each database
          include_tasks: tasks/backup_single_db.yaml
          loop: "{{ db_names }}"
          loop_control:
            loop_var: _current_db
          when: not ansible_check_mode

      rescue:
        - name: Set database backup failed flag
          ansible.builtin.set_fact:
            backup_db_failed: true

      always:
        - name: Build combined notification fields for backup results
          ansible.builtin.set_fact:
            _db_discord_fields: >-
              [
               {% for r in combined_results %}
               {% if not loop.first %},{% endif %}
               {"name": "{{ ('❌ ' if r.backup_rc != 0 else '✅ ') + r.db_name }}",
                "value": "{{ 'FAILED' if r.backup_rc != 0 else ((r.file_size / 1024 / 1024) | round(2) | string + ' MB') }}",
                "inline": true}
               {% endfor %}]
          when: combined_results | length > 0

        - name: Send combined DB backup notification
          include_tasks: tasks/notify.yaml
          vars:
            discord_name: "{{ backup_name }}"
            discord_operation: "Backup"
            discord_status: >-
              {{ 'successful' if (combined_results | selectattr('backup_rc', 'ne', 0) | list | length == 0)
                 else ('failed' if (combined_results | selectattr('backup_rc', 'eq', 0) | list | length == 0)
                       else 'partial') }}
            discord_color: >-
              {{ discord_color_success if (combined_results | selectattr('backup_rc', 'ne', 0) | list | length == 0)
                 else (discord_color_failure if (combined_results | selectattr('backup_rc', 'eq', 0) | list | length == 0)
                       else discord_color_warning) }}
            discord_url: "{{ backup_url }}"
            discord_fields: "{{ _db_discord_fields }}"
          when: combined_results | length > 0

        - name: Send notification for unhandled block error
          include_tasks: tasks/notify.yaml
          when: backup_db_failed and combined_results | length == 0
          vars:
            discord_name: "{{ backup_name }}"
            discord_operation: "Backup"
            discord_status: "failed"
            discord_detail: "check Semaphore logs"
            discord_color: "{{ discord_color_failure }}"
            discord_url: "{{ backup_url }}"

        - name: Log DB backup results to MariaDB
          include_tasks: tasks/log_mariadb.yaml
          loop: "{{ combined_results }}"
          loop_control:
            loop_var: _db_result
          vars:
            log_table: backups
            log_application: "{{ _db_result.db_name }}-db"
            log_hostname: "{{ inventory_hostname }}"
            log_file_name: "{{ ('FAILED_' if _db_result.backup_rc != 0 else '') + _db_result.file_name }}"
            log_file_size: "{{ (_db_result.file_size / 1024 / 1024) | round(2) if _db_result.backup_rc == 0 else 0 }}"
            log_backup_level: "db"

        # ===== CLEANUP RUN-SCOPED TEMP DIRECTORY =====
        - name: Remove run-scoped temp directory
          become: true
          ansible.builtin.file:
            state: absent
            path: "{{ backup_tmp_dir }}"
          when: "'/run_' in backup_tmp_dir"
