---
# Manage Ubuntu VMs on Proxmox via API.
# Play 1 (localhost): Create, destroy, snapshot, or revert a VM.
# Play 2 (new VM): Bootstrap Ubuntu with Docker and security hardening.
# Deploy stacks separately via deploy_stacks.yaml after provisioning.
#
# The cloud-init template is created automatically on first run (one-time per cluster).
# It downloads the Ubuntu Noble cloud image and converts it to a Proxmox template
# on Ceph (replicated) storage, accessible from all nodes.
#
# Usage:
#   ansible-playbook build_ubuntu.yaml -e vm_name=test-vm
#   ansible-playbook build_ubuntu.yaml -e vm_name=test-vm -e vm_state=absent
#   ansible-playbook build_ubuntu.yaml -e vm_name=test-vm -e vm_state=snapshot -e snapshot_name=post-bootstrap
#   ansible-playbook build_ubuntu.yaml -e vm_name=test-vm -e vm_state=revert -e snapshot_name=post-bootstrap
#
# Required extra vars:
#   vm_name — key in vm_definitions (tantiveiv, odyssey, amp, test-vm)
#
# Optional extra vars:
#   vm_state=absent   — destroy VM instead of creating
#   vm_state=snapshot — create a named Proxmox snapshot (disk only, no RAM)
#   vm_state=revert   — revert to a named snapshot, restart VM, wait for SSH
#   snapshot_name     — required when vm_state is snapshot or revert

# ═══════════════════════════════════════════════════════════════════
# Play 1 — Manage VM on Proxmox (create / destroy / snapshot / revert)
# ═══════════════════════════════════════════════════════════════════
- name: Manage Ubuntu VM on Proxmox
  hosts: localhost
  gather_facts: true
  gather_subset: ['!all', 'date_time']
  vars_files:
    - vars/secrets.yaml
    - vars/vm_definitions.yaml
  vars:
    maintenance_name: "Ubuntu"
    maintenance_type: "Servers"
    maintenance_subtype: "Build"

  pre_tasks:
    - name: Assert vm_name is defined and exists in vm_definitions
      ansible.builtin.assert:
        that:
          - vm_name is defined
          - vm_name in vm_definitions
        fail_msg: >-
          vm_name '{{ vm_name | default('undefined') }}' not found in vm_definitions.
          Valid names: {{ vm_definitions.keys() | list | join(', ') }}

    - name: Resolve VM definition
      ansible.builtin.set_fact:
        _vm: "{{ vm_definitions[vm_name] }}"
        _vm_state: "{{ vm_state | default('present') }}"

    - name: Assert snapshot_name is defined for snapshot/revert
      ansible.builtin.assert:
        that:
          - snapshot_name is defined
          - snapshot_name | length > 0
        fail_msg: "snapshot_name is required when vm_state is {{ _vm_state }}"
      when: _vm_state in ['snapshot', 'revert']

    - name: Assert MariaDB logging database is reachable
      include_tasks: tasks/assert_db_connectivity.yaml

  tasks:
    - name: Initialize build state
      ansible.builtin.set_fact:
        build_failed: false
        _build_detail: ""

    - block:
        # ═════════════════════════════════════════════════════════
        # CREATE PATH — vm_state == 'present' (default)
        # ═════════════════════════════════════════════════════════
        - name: Provision VM on Proxmox
          include_tasks: tasks/provision_vm.yaml
          when: _vm_state == 'present'

        # ═════════════════════════════════════════════════════════
        # DESTROY PATH — vm_state == 'absent'
        # ═════════════════════════════════════════════════════════
        - name: Stop VM
          community.general.proxmox_kvm:
            api_host: "{{ pve_api_host }}"
            api_user: "{{ pve_api_user }}"
            api_token_id: "{{ pve_api_token_id }}"
            api_token_secret: "{{ pve_api_token_secret }}"
            node: "{{ _vm.pve_target_node }}"
            vmid: "{{ _vm.vm_id }}"
            state: stopped
            force: true
          no_log: true
          when: _vm_state == 'absent'

        - name: Remove VM
          community.general.proxmox_kvm:
            api_host: "{{ pve_api_host }}"
            api_user: "{{ pve_api_user }}"
            api_token_id: "{{ pve_api_token_id }}"
            api_token_secret: "{{ pve_api_token_secret }}"
            node: "{{ _vm.pve_target_node }}"
            vmid: "{{ _vm.vm_id }}"
            state: absent
          no_log: true
          when: _vm_state == 'absent'

        # ═════════════════════════════════════════════════════════
        # SNAPSHOT PATH — vm_state == 'snapshot'
        # ═════════════════════════════════════════════════════════
        - name: Create VM snapshot
          ansible.builtin.uri:
            url: "https://{{ pve_api_host }}:8006/api2/json/nodes/{{ _vm.pve_target_node }}/qemu/{{ _vm.vm_id }}/snapshot"
            method: POST
            headers:
              Authorization: "PVEAPIToken={{ pve_api_user }}!{{ pve_api_token_id }}={{ pve_api_token_secret }}"
            body_format: form-urlencoded
            body:
              snapname: "{{ snapshot_name }}"
              vmstate: 0
            validate_certs: false
          no_log: true
          when: _vm_state == 'snapshot'

        # ═════════════════════════════════════════════════════════
        # REVERT PATH — vm_state == 'revert'
        # ═════════════════════════════════════════════════════════
        - name: Stop VM before revert
          community.general.proxmox_kvm:
            api_host: "{{ pve_api_host }}"
            api_user: "{{ pve_api_user }}"
            api_token_id: "{{ pve_api_token_id }}"
            api_token_secret: "{{ pve_api_token_secret }}"
            node: "{{ _vm.pve_target_node }}"
            vmid: "{{ _vm.vm_id }}"
            state: stopped
            force: true
          no_log: true
          ignore_errors: true
          when: _vm_state == 'revert'

        - name: Revert VM to snapshot
          ansible.builtin.uri:
            url: "https://{{ pve_api_host }}:8006/api2/json/nodes/{{ _vm.pve_target_node }}/qemu/{{ _vm.vm_id }}/snapshot/{{ snapshot_name }}/rollback"
            method: POST
            headers:
              Authorization: "PVEAPIToken={{ pve_api_user }}!{{ pve_api_token_id }}={{ pve_api_token_secret }}"
            validate_certs: false
          no_log: true
          when: _vm_state == 'revert'

        - name: Start VM after revert
          community.general.proxmox_kvm:
            api_host: "{{ pve_api_host }}"
            api_user: "{{ pve_api_user }}"
            api_token_id: "{{ pve_api_token_id }}"
            api_token_secret: "{{ pve_api_token_secret }}"
            node: "{{ _vm.pve_target_node }}"
            vmid: "{{ _vm.vm_id }}"
            state: started
          no_log: true
          when: _vm_state == 'revert'

        - name: Wait for SSH after revert
          ansible.builtin.wait_for:
            host: "{{ _vm.vm_ip }}"
            port: 22
            delay: 5
            timeout: 120
          when: _vm_state == 'revert'

        - name: Record build detail
          ansible.builtin.set_fact:
            _build_detail: >-
              {% if _vm_state == 'absent' %}VM destroyed{% elif _vm_state == 'snapshot' %}Snapshot '{{ snapshot_name }}' created{% elif _vm_state == 'revert' %}Reverted to '{{ snapshot_name }}'{% else %}VM provisioned{% endif %}:
              {{ _vm.vm_name }} ({{ _vm.vm_ip }}) on {{ _vm.pve_target_node }}

      rescue:
        - name: Set build failed flag
          ansible.builtin.set_fact:
            build_failed: true
            _build_detail: "{{ ansible_failed_result.msg | default('check Semaphore logs') }}"

      always:
        - name: Send Discord notification
          include_tasks: tasks/notify_discord.yaml
          vars:
            discord_name: "{{ maintenance_name }}"
            discord_operation: "Build"
            discord_status: "{{ 'failed' if build_failed else 'successful' }}"
            discord_color: "{{ discord_color_failure if build_failed else discord_color_success }}"
            discord_url: "{{ semaphore_ext_url }}"
            discord_author: "{{ controller_fqdn }}"
            discord_fields:
              - name: "VM Name"
                value: "{{ _vm.vm_name }}"
              - name: "Host IP"
                value: "{{ _vm.vm_ip }}"
              - name: "Proxmox Node"
                value: "{{ _vm.pve_target_node }}"
              - name: "Detail"
                value: "{{ _build_detail }}"

        - name: Log build to MariaDB
          include_tasks: tasks/log_mariadb.yaml
          vars:
            log_table: maintenance
            log_application: "{{ maintenance_name }}"
            log_hostname: "{{ controller_fqdn }}"
            log_type: "{{ maintenance_type }}"
            log_subtype: "{{ maintenance_subtype }}"
            log_status: "{{ 'failed' if build_failed else 'success' }}"

        - name: Fail play if build failed
          ansible.builtin.fail:
            msg: "Build failed: {{ _build_detail }}"
          when: build_failed

# ═══════════════════════════════════════════════════════════════════
# Play 2 — Bootstrap Ubuntu (skipped when vm_state=absent)
# ═══════════════════════════════════════════════════════════════════
- name: Bootstrap Ubuntu VM
  hosts: build_target
  become: true
  gather_facts: true
  vars_files:
    - vars/secrets.yaml
    - vars/vm_definitions.yaml
  vars:
    maintenance_name: "Ubuntu"
    maintenance_type: "Servers"
    maintenance_subtype: "Build"

  tasks:
    - name: Initialize bootstrap state
      ansible.builtin.set_fact:
        bootstrap_failed: false
        _bootstrap_detail: ""

    - block:
        - name: Bootstrap Ubuntu with Docker and security hardening
          include_tasks: tasks/bootstrap_vm.yaml
          vars:
            _vm: "{{ hostvars['localhost']._vm }}"

        - name: Record bootstrap detail
          ansible.builtin.set_fact:
            _bootstrap_detail: "Bootstrap complete — Docker, security hardening"

      rescue:
        - name: Set bootstrap failed flag
          ansible.builtin.set_fact:
            bootstrap_failed: true
            _bootstrap_detail: "{{ ansible_failed_result.msg | default('check Semaphore logs') }}"

      always:
        - name: Send Discord notification
          include_tasks: tasks/notify_discord.yaml
          vars:
            discord_name: "{{ maintenance_name }}"
            discord_operation: "Bootstrap"
            discord_status: "{{ 'failed' if bootstrap_failed else 'successful' }}"
            discord_color: "{{ discord_color_failure if bootstrap_failed else discord_color_success }}"
            discord_url: "{{ semaphore_ext_url }}"
            discord_fields:
              - name: "Detail"
                value: "{{ _bootstrap_detail }}"

        - name: Log bootstrap to MariaDB
          include_tasks: tasks/log_mariadb.yaml
          vars:
            log_table: maintenance
            log_application: "{{ maintenance_name }}"
            log_hostname: "{{ inventory_hostname }}"
            log_type: "{{ maintenance_type }}"
            log_subtype: "{{ maintenance_subtype }}"
            log_status: "{{ 'failed' if bootstrap_failed else 'success' }}"

        - name: Fail play if bootstrap failed
          ansible.builtin.fail:
            msg: "Bootstrap failed: {{ _bootstrap_detail }}"
          when: bootstrap_failed
