---
# Deploy Docker stacks from Git to target hosts.
# Templates .env from vault, copies compose files, validates, and starts stacks.
# Stacks deploy in stack_assignments order — databases before auth, etc.
#
# Usage:
#   ansible-playbook deploy_stacks.yaml -e hosts_variable=docker_stacks --limit tantiveiv
#
# Optional extra vars:
#   deploy_stack=infra    — deploy a single stack instead of all assigned stacks
#   validate_only=yes     — render and validate only, skip docker compose up
#   debug_no_log=yes      — show template output in logs (NEVER in production)

- name: Deploy Docker stacks from Git
  hosts: "{{ hosts_variable }}"
  gather_facts: true
  gather_subset: ['!all', 'date_time']
  serial: 1
  vars_files:
    - vars/secrets.yaml
    - vars/{{ config_file }}.yaml
    - vars/docker_vips.yaml
    - vars/semaphore_check.yaml
  vars:
    config_file: "{{ hosts_variable }}"
    maintenance_name: "Docker"
    maintenance_type: "Servers"
    maintenance_subtype: "Deploy"

  pre_tasks:
    - name: Assert config_file is defined and non-empty
      include_tasks: tasks/assert_config_file.yaml

    - name: Inject test VM role (test_vm_role override)
      ansible.builtin.set_fact:
        vault_vm_roles: "{{ vault_vm_roles | combine({inventory_hostname: test_vm_role}) }}"
        vault_docker_vrrp_priorities: >-
          {{ vault_docker_vrrp_priorities | default({})
             | combine({inventory_hostname.split('.')[0]: 100}) }}
      when: test_vm_role is defined

    - name: Assert host has a role assignment
      ansible.builtin.assert:
        that:
          - inventory_hostname in vault_vm_roles
        fail_msg: >-
          {{ inventory_hostname }} is not in vault_vm_roles. Add a role mapping
          (e.g. vault_vm_roles: { {{ inventory_hostname }}: core }) before deploying.

    - name: Assert host has stack assignments
      ansible.builtin.assert:
        that: inventory_hostname in stack_assignments
        fail_msg: >-
          No stack_assignments entry for {{ inventory_hostname }}.
          Check vault_vm_roles and stack_roles in vars/docker_stacks.yaml.
      when: deploy_stack | default('') | length == 0

    - name: Assert sufficient disk space on target
      include_tasks: tasks/assert_disk_space.yaml
      vars:
        assert_disk_path: /opt
        assert_disk_min_gb: "{{ backup_assert_disk_min_gb | default(1) }}"

    - name: Assert MariaDB logging database is reachable
      include_tasks: tasks/assert_db_connectivity.yaml

    - name: Log playbook run context to MariaDB
      include_tasks: tasks/log_run_context.yaml
      vars:
        log_playbook: "deploy_stacks.yaml"
        log_hostname: "{{ inventory_hostname }}"
        log_run_vars: "{}"

  tasks:
    - name: Initialize deploy state
      ansible.builtin.set_fact:
        deploy_failed: false
        _deploy_detail: ""
        _deploy_stacks: >-
          {{ [deploy_stack] if deploy_stack | default('') | length > 0
             else stack_assignments[inventory_hostname] }}

    - name: Ensure shared Docker network exists
      community.docker.docker_network:
        name: homelab
        state: present
      become: true

    - block:
        - name: Check for port conflicts across stacks
          ansible.builtin.shell: |
            conflicts=""
            declare -A port_map
            for stack in {{ _deploy_stacks | join(' ') }}; do
              cd "/opt/stacks/$stack" 2>/dev/null || continue
              ports=$(docker compose config 2>/dev/null | grep -oP 'published: "\K\d+' | sort -u)
              for port in $ports; do
                if [ -n "${port_map[$port]:-}" ]; then
                  conflicts="$conflicts Port $port: ${port_map[$port]} vs $stack;"
                fi
                port_map[$port]="$stack"
              done
            done
            if [ -n "$conflicts" ]; then
              echo "$conflicts"
              exit 1
            fi
          args:
            executable: /bin/bash
          become: true
          when:
            - inventory_hostname in groups["docker_stacks"] | default([])
            - _deploy_stacks | length > 1
          register: _port_check
          failed_when: _port_check.rc | default(0) != 0
          changed_when: false
          check_mode: false

        - name: Deploy stacks
          include_tasks: tasks/deploy_single_stack.yaml
          loop: "{{ _deploy_stacks }}"
          loop_control:
            loop_var: _current_stack

        - name: Verify Docker network connectivity
          include_tasks: tasks/verify_docker_network.yaml
          when: not ansible_check_mode

        - name: Verify VIP is active
          include_tasks: tasks/verify_vip.yaml
          when: not ansible_check_mode

        - name: Record deploy detail
          ansible.builtin.set_fact:
            _deploy_detail: "Stacks deployed: {{ _deploy_stacks | join(', ') }}"

      rescue:
        - name: Set deploy failed flag
          ansible.builtin.set_fact:
            deploy_failed: true
            _deploy_detail: "{{ ansible_failed_result.msg | default('check Semaphore logs') }}"

      always:
        - name: Send Discord notification
          include_tasks: tasks/notify.yaml
          vars:
            discord_name: "{{ maintenance_name }}"
            discord_operation: "Deploy"
            discord_status: "{{ 'failed' if deploy_failed else 'successful' }}"
            discord_color: "{{ discord_color_failure if deploy_failed else discord_color_success }}"
            discord_url: "{{ semaphore_ext_url }}"
            discord_fields:
              - name: "Stacks"
                value: "{{ _deploy_stacks | join(', ') }}"
              - name: "Detail"
                value: "{{ _deploy_detail }}"

        - name: Log deploy to MariaDB
          include_tasks: tasks/log_mariadb.yaml
          vars:
            log_table: maintenance
            log_application: "{{ maintenance_name }}"
            log_hostname: "{{ inventory_hostname }}"
            log_type: "{{ maintenance_type }}"
            log_subtype: "{{ maintenance_subtype }}"
            log_status: "{{ 'failed' if deploy_failed else 'success' }}"

        - name: Fail play if deploy failed
          ansible.builtin.fail:
            msg: "Deploy failed: {{ _deploy_detail }}"
          when: deploy_failed
