---
# Idempotent Proxmox node configuration — run after bare-metal reinstall or new node join.
# Ensures OS-level settings not managed by PVE cluster replication are in expected state:
# keepalived VIP (PVE nodes), ansible user SSH key, SSH hardening (PVE and PBS).
#
# Firewall rules and storage config are stored in /etc/pve/ (cluster-replicated via Corosync)
# and are restored automatically when a node re-joins the cluster — no Ansible action needed.
#
# Usage (safe to re-run — idempotent):
#   ansible-playbook maintain_pve.yaml
#
# Required vault vars: vault_pve_vip, vault_pve_vrrp_password, vault_pve_vrrp_priorities,
#                       ansible_user_ssh_pubkey

# ═══════════════════════════════════════════════════════════════════
# Play 1 — Maintain Proxmox node OS-level configuration
# ═══════════════════════════════════════════════════════════════════
- name: Maintain Proxmox node configuration
  hosts: "pve:pbs"
  become: true
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
    - vars/proxmox.yaml
  vars:
    maintenance_name: "Proxmox"
    maintenance_type: "Appliances"
    maintenance_subtype: "Maintenance"
    maintenance_url: ""
    maintenance_description: "Ensure Proxmox nodes are in expected configuration state"

  pre_tasks:
    - name: Assert MariaDB logging database is reachable
      include_tasks: tasks/assert_db_connectivity.yaml

  tasks:
    - name: Initialize maintenance state
      ansible.builtin.set_fact:
        maintenance_failed: false

    - block:
        # === Keepalived VIP (PVE nodes only — not needed on PBS) ===
        - name: Install keepalived
          ansible.builtin.apt:
            name: keepalived
            state: present
            update_cache: true
          when: inventory_hostname in groups["pve"]

        - name: Template keepalived config
          ansible.builtin.template:
            src: templates/keepalived.conf.j2
            dest: /etc/keepalived/keepalived.conf
            owner: root
            group: root
            mode: "0640"
          notify: Restart keepalived
          when: inventory_hostname in groups["pve"]

        - name: Enable and start keepalived
          ansible.builtin.service:
            name: keepalived
            state: started
            enabled: true
          when: inventory_hostname in groups["pve"]

        # === Ansible user SSH key (PVE and PBS) ===
        - name: Install sudo
          ansible.builtin.apt:
            name: sudo
            state: present

        - name: Add ansible user
          ansible.builtin.user:
            name: ansible
            comment: ansible

        - name: Add ansible user to sudo group
          ansible.builtin.user:
            name: ansible
            groups: sudo
            append: true

        - name: Deploy SSH public key for ansible user
          ansible.builtin.authorized_key:
            user: ansible
            key: "{{ ansible_user_ssh_pubkey }}"
            state: present

        - name: Harden SSH and configure passwordless sudo
          include_tasks: tasks/ssh_hardening.yaml
          vars:
            _ssh_user: ansible
            _ssh_service_name: sshd

      rescue:
        - name: Set maintenance failed
          ansible.builtin.set_fact:
            maintenance_failed: true

      always:
        - name: Flush handlers (restart keepalived if config changed)
          meta: flush_handlers

        - name: Send Discord alert on failure
          include_tasks: tasks/notify.yaml
          when: maintenance_failed
          vars:
            discord_name: "{{ maintenance_name }}"
            discord_operation: "Maintenance"
            discord_status: "failed"
            discord_detail: "check Semaphore logs"
            discord_color: "{{ discord_color_failure }}"
            discord_url: "{{ maintenance_url }}"

        - name: Log maintenance to MariaDB
          include_tasks: tasks/log_mariadb.yaml
          vars:
            log_table: "maintenance"
            log_application: "{{ maintenance_name }}"
            log_hostname: "{{ inventory_hostname }}"
            log_type: "{{ maintenance_type }}"
            log_subtype: "{{ maintenance_subtype }}"
            log_status: "{{ 'failed' if maintenance_failed else 'success' }}"

  handlers:
    - name: Restart keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted

# ═══════════════════════════════════════════════════════════════════
# Play 2 — Verify VIP is reachable from the controller
# ═══════════════════════════════════════════════════════════════════
- name: Verify VIP is reachable
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
    - vars/proxmox.yaml

  tasks:
    - name: Wait for VIP to respond on port 22 (SSH via MASTER node)
      ansible.builtin.wait_for:
        host: "{{ vault_pve_vip }}"
        port: 22
        timeout: 15
        msg: "VIP {{ vault_pve_vip }} is not reachable on port 22 — keepalived may not have converged"
      when: not ansible_check_mode

    - name: VIP is up
      ansible.builtin.debug:
        msg: "VIP {{ vault_pve_vip }} is reachable. keepalived is healthy."

# ═══════════════════════════════════════════════════════════════════
# Play 3 — Check for stale VM snapshots (older than 14 days)
# ═══════════════════════════════════════════════════════════════════
- name: Check Proxmox for stale VM snapshots
  hosts: localhost
  gather_facts: true
  vars_files:
    - vars/secrets.yaml
    - vars/semaphore_check.yaml
  vars:
    snapshot_max_age_days: 14
    maintenance_name: "Proxmox"
    maintenance_type: "Appliances"
    maintenance_subtype: "Snapshot Check"

  pre_tasks:
    - name: Assert MariaDB logging database is reachable
      include_tasks: tasks/assert_db_connectivity.yaml

  tasks:
    - name: Initialize stale snapshot state
      ansible.builtin.set_fact:
        _stale_snapshots: []

    # ===== FETCH CLUSTER VM LIST =====
    - name: Get all cluster VMs
      ansible.builtin.uri:
        url: "https://{{ vault_pve_vip }}:8006/api2/json/cluster/resources?type=vm"
        method: GET
        headers:
          Authorization: "PVEAPIToken={{ pve_api_user }}!{{ pve_api_token_id }}={{ pve_api_token_secret }}"
        validate_certs: false
      register: _cluster_vms
      no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"

    # ===== FETCH SNAPSHOTS PER VM =====
    - name: Get snapshots for each QEMU VM
      ansible.builtin.uri:
        url: "https://{{ vault_pve_vip }}:8006/api2/json/nodes/{{ item.node }}/qemu/{{ item.vmid }}/snapshot"
        method: GET
        headers:
          Authorization: "PVEAPIToken={{ pve_api_user }}!{{ pve_api_token_id }}={{ pve_api_token_secret }}"
        validate_certs: false
      register: _snapshot_results
      loop: "{{ _cluster_vms.json.data | selectattr('type', 'equalto', 'qemu') | list }}"
      loop_control:
        label: "{{ item.name }} ({{ item.vmid }})"
      no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"
      ignore_errors: true

    # ===== IDENTIFY STALE SNAPSHOTS =====
    - name: Compute stale snapshot threshold (epoch minus max age)
      ansible.builtin.set_fact:
        _snapshot_threshold: "{{ (ansible_date_time.epoch | int) - (snapshot_max_age_days | int * 86400) }}"

    - name: Build stale snapshot list
      ansible.builtin.set_fact:
        _stale_snapshots: >-
          {{ _stale_snapshots +
             (item.json.data
              | selectattr('name', 'ne', 'current')
              | selectattr('snaptime', 'defined')
              | selectattr('snaptime', 'lt', _snapshot_threshold | int)
              | map('combine', {'vm': item.item.name, 'vmid': item.item.vmid})
              | list) }}
      loop: "{{ _snapshot_results.results | selectattr('failed', 'equalto', false) | list }}"
      loop_control:
        label: "{{ item.item.name }} ({{ item.item.vmid }})"
      when: item.json is defined

    # ===== REPORT =====
    - name: Format stale snapshot list for Discord
      ansible.builtin.set_fact:
        _stale_msg: |
          {% for s in _stale_snapshots -%}
          {{ s.vm }} ({{ s.vmid }}): {{ s.name }} — {{ ((ansible_date_time.epoch | int - s.snaptime) / 86400) | int }}d old
          {% endfor %}
      when: _stale_snapshots | length > 0

    - name: Send Discord alert for stale snapshots
      include_tasks: tasks/notify.yaml
      when: _stale_snapshots | length > 0
      vars:
        discord_name: "{{ maintenance_name }}"
        discord_operation: "Snapshot Check"
        discord_status: "warning"
        discord_detail: "{{ _stale_snapshots | length }} snapshot(s) older than {{ snapshot_max_age_days }} days"
        discord_color: "{{ discord_color_warning }}"
        discord_url: "{{ semaphore_ext_url }}"
        discord_author: "{{ controller_fqdn }}"
        discord_fields:
          - name: "Stale Snapshots (>{{ snapshot_max_age_days }}d)"
            value: "{{ _stale_msg | trim }}"

    - name: Log snapshot check to MariaDB
      include_tasks: tasks/log_mariadb.yaml
      vars:
        log_table: maintenance
        log_application: "{{ maintenance_name }}"
        log_hostname: "{{ controller_fqdn }}"
        log_type: "{{ maintenance_type }}"
        log_subtype: "{{ maintenance_subtype }}"
        log_status: "{{ 'warning' if _stale_snapshots | length > 0 else 'success' }}"
