---
# Purge failure and stale records from ansible_logging.
# Deletes failed updates, failed maintenance, zero-size backups, and
# warning/critical health checks recorded before this run.
# Run ad-hoc after testing phases to clear noise from production dashboards.

- name: Purge stale failures from ansible_logging
  hosts: localhost
  gather_facts: true
  gather_subset: ['!all', 'date_time']
  vars_files:
    - vars/secrets.yaml
    - vars/semaphore_check.yaml
  vars:
    maintenance_name: "Logging DB"
    maintenance_type: "Local"
    maintenance_subtype: "Cleanup"
    maintenance_url: ""
    maintenance_description: "Delete failed/warning records from ansible_logging prior to now"

  pre_tasks:
    - name: Run standard pre-flight assertions
      include_tasks: tasks/pre_task_assertions.yaml
      vars:
        pre_playbook: "maintain_logging_db.yaml"
        pre_hostname: "{{ controller_fqdn }}"

  tasks:
    - name: Initialize maintenance state
      ansible.builtin.set_fact:
        maintenance_failed: false

    - block:
        - name: Purge ansible_logging failure records
          vars:
            ansible_python_interpreter: "{{ ansible_playbook_python }}"
          become: false
          connection: local
          when: not ansible_check_mode
          community.mysql.mysql_query:
            login_host: "{{ logging_db_host }}"
            login_port: "{{ logging_db_port }}"
            login_user: "{{ logging_db_user }}"
            login_password: "{{ logging_db_password }}"
            login_db: "{{ logging_db_name }}"
            query: "{{ item }}"
          loop:
            - "DELETE FROM updates WHERE status = 'failed' AND timestamp < UTC_TIMESTAMP()"
            - "DELETE FROM maintenance WHERE status = 'failed' AND timestamp < UTC_TIMESTAMP()"
            - "DELETE FROM backups WHERE file_size = 0 AND timestamp < UTC_TIMESTAMP()"
            - "DELETE FROM health_checks WHERE check_status IN ('warning', 'critical') AND timestamp < UTC_TIMESTAMP()"
          loop_control:
            label: "{{ item.split('FROM ')[1].split(' WHERE')[0] }}"
          no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"

      rescue:
        - name: Set maintenance failed
          ansible.builtin.set_fact:
            maintenance_failed: true

      always:
        - name: Send alert on failure
          include_tasks: tasks/notify.yaml
          when: maintenance_failed
          vars:
            discord_name: "{{ maintenance_name }}"
            discord_operation: "Maintenance"
            discord_status: "failed"
            discord_detail: "check Semaphore logs"
            discord_color: "{{ discord_color_failure }}"
            discord_url: "{{ maintenance_url }}"
            discord_author: "{{ controller_fqdn }}"

        - name: Log maintenance to MariaDB
          include_tasks: tasks/log_mariadb.yaml
          vars:
            log_table: maintenance
            log_application: "{{ maintenance_name }}"
            log_hostname: "{{ controller_fqdn }}"
            log_type: "{{ maintenance_type }}"
            log_subtype: "{{ maintenance_subtype }}"
            log_status: "{{ 'failed' if maintenance_failed else 'success' }}"
