---
# AMP Server Maintenance Playbook
# Cleans up old AMP versions, Docker images, crash dumps, and journal logs.
#
# Usage:
#   ansible-playbook maintain_amp.yaml
#   ansible-playbook maintain_amp.yaml -e amp_scope=versions
#   ansible-playbook maintain_amp.yaml -e amp_versions_keep=3
#
# Optional extra vars:
#   amp_scope=versions|cleanup|coredumps|prune|journal  — run only this scope (default: all)
#
# Schedule with Semaphore to run weekly.

- name: Maintain AMP game servers
  hosts: amp
  gather_facts: true
  become: true
  vars_files:
    - vars/secrets.yaml
    - vars/amp.yaml
  vars:
    amp_versions_dir: "{{ amp_home }}/.ampdata/Versions/Mainline"
    maintenance_name: "AMP"
    maintenance_type: "Servers"
    maintenance_subtype: "Maintenance"
    maintenance_url: "https://{{ inventory_hostname.split('.')[0] }}.{{ domain_ext }}"
    maintenance_description: "AMP game server maintenance (versions, core dumps, Docker prune, journal, tmp)"

  pre_tasks:
    - name: Run standard pre-flight assertions
      include_tasks: tasks/pre_task_assertions.yaml
      vars:
        pre_playbook: "maintain_amp.yaml"

  tasks:
    - name: Initialize maintenance state
      ansible.builtin.set_fact:
        maintenance_failed: false

    - block:
        # ── AMP Old Versions ──────────────────────────────────────────────
        - name: Get list of AMP versions sorted newest first
          ansible.builtin.shell: |
            ls -1t {{ amp_versions_dir }}
          register: _amp_versions
          changed_when: false
          check_mode: false
          when: amp_scope is not defined or amp_scope == 'versions'

        - name: Identify old AMP versions to remove
          ansible.builtin.set_fact:
            amp_versions_to_remove: "{{ _amp_versions.stdout_lines[amp_versions_keep:] }}"
          when: amp_scope is not defined or amp_scope == 'versions'

        - name: Display versions to remove
          ansible.builtin.debug:
            msg: "Removing {{ amp_versions_to_remove | length }} old version(s): {{ amp_versions_to_remove | join(', ') }}"
          when:
            - amp_scope is not defined or amp_scope == 'versions'
            - amp_versions_to_remove | length > 0

        - name: Remove old AMP versions
          ansible.builtin.file:
            path: "{{ amp_versions_dir }}/{{ item }}"
            state: absent
          loop: "{{ amp_versions_to_remove }}"
          when: amp_scope is not defined or amp_scope == 'versions'

        # ── instances.json .bak rotation ─────────────────────────────────
        - name: Find old instances.json .bak files
          ansible.builtin.find:
            paths: "{{ amp_home }}/.ampdata"
            patterns: "instances.json-*.bak"
            file_type: file
          register: _amp_bak_files
          when: amp_scope is not defined or amp_scope == 'cleanup'

        - name: Remove old instances.json .bak files (keep {{ amp_versions_keep }} newest)
          ansible.builtin.file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ (_amp_bak_files.files | sort(attribute='mtime') | reverse | list)[amp_versions_keep:] }}"
          when:
            - amp_scope is not defined or amp_scope == 'cleanup'
            - _amp_bak_files.matched > amp_versions_keep

        # ── Crash Core Dumps ──────────────────────────────────────────────
        - name: Find core dump files in AMP instances
          ansible.builtin.find:
            paths: "{{ amp_home }}/.ampdata/instances"
            patterns: "core*"
            file_type: file
            recurse: true
          register: _core_dumps
          when: amp_scope is not defined or amp_scope == 'coredumps'

        - name: Remove core dump files
          ansible.builtin.file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ _core_dumps.files }}"
          when:
            - amp_scope is not defined or amp_scope == 'coredumps'
            - _core_dumps.matched > 0

        # ── Instance Log Rotation ─────────────────────────────────────────
        - name: Find old AMP instance log files (older than 30 days)
          ansible.builtin.find:
            paths: "{{ amp_home }}/.ampdata/instances"
            patterns: "*.log,*.log.*"
            file_type: file
            recurse: true
            age: 30d
          register: _amp_logs
          when: amp_scope is not defined or amp_scope == 'cleanup'

        - name: Remove old AMP instance log files
          ansible.builtin.file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ _amp_logs.files }}"
          when:
            - amp_scope is not defined or amp_scope == 'cleanup'
            - _amp_logs.matched > 0

        # ── Docker Cleanup ────────────────────────────────────────────────
        - name: Prune unused Docker images
          community.docker.docker_prune:
            images: true
            images_filters:
              dangling: "false"
          ignore_errors: true
          when: amp_scope is not defined or amp_scope == 'prune'

        # ── Journal Logs ──────────────────────────────────────────────────
        - name: Vacuum old journal logs
          ansible.builtin.command:
            cmd: journalctl --vacuum-time={{ amp_journal_max_age }}
          register: journal_result
          changed_when: "'freed' in journal_result.stderr and 'freed 0B' not in journal_result.stderr"
          when: amp_scope is not defined or amp_scope == 'journal'

        # ── Temp Backup Cleanup ───────────────────────────────────────────
        - name: Remove stale backup files from /tmp
          ansible.builtin.find:
            paths: /tmp/backup
            patterns: "*.tar.gz"
            age: 1d
          register: _tmp_backups
          when: amp_scope is not defined or amp_scope == 'cleanup'

        - name: Delete stale /tmp backups
          ansible.builtin.file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ _tmp_backups.files }}"
          when:
            - amp_scope is not defined or amp_scope == 'cleanup'
            - _tmp_backups.matched > 0

      rescue:
        - name: Set maintenance failed
          ansible.builtin.set_fact:
            maintenance_failed: true

      always:
        - name: Send Discord alert on failure
          include_tasks: tasks/notify.yaml
          when: maintenance_failed
          vars:
            discord_name: "{{ maintenance_name }}"
            discord_operation: "Maintenance"
            discord_status: "failed"
            discord_detail: "check Semaphore logs"
            discord_color: "{{ discord_color_failure }}"
            discord_url: "{{ maintenance_url }}"

        - name: Log maintenance to MariaDB
          include_tasks: tasks/log_mariadb.yaml
          vars:
            log_table: "maintenance"
            log_application: "{{ maintenance_name }}"
            log_hostname: "{{ inventory_hostname }}"
            log_type: "{{ maintenance_type }}"
            log_subtype: "{{ maintenance_subtype }}"
            log_status: "{{ 'failed' if maintenance_failed else 'success' }}"
