---
# Prune unused Docker images across all Docker hosts.
# Uses community.docker.docker_prune to remove dangling images.
# Schedule with Semaphore to run weekly.

- name: Prune unused Docker images
  hosts: "docker"
  gather_facts: true
  gather_subset: ['!all', 'date_time']
  vars_files:
    - vars/secrets.yaml
  vars:
    maintenance_name: "Docker"
    maintenance_type: "Servers"
    maintenance_subtype: "Prune"
    maintenance_url: ""
    maintenance_description: "Prune unused Docker images across all Docker hosts"

  pre_tasks:
    - name: Assert MariaDB logging database is reachable
      include_tasks: tasks/assert_db_connectivity.yaml

  tasks:
    - name: Initialize maintenance state
      ansible.builtin.set_fact:
        maintenance_failed: false

    - block:
        - name: Prune unused Docker images
          become: true
          community.docker.docker_prune:
            images: true
            images_filters:
              dangling: "false"

      rescue:
        - name: Set maintenance failed
          ansible.builtin.set_fact:
            maintenance_failed: true

      always:
        - name: Send Discord alert on failure
          include_tasks: tasks/notify_discord.yaml
          when: maintenance_failed
          vars:
            discord_name: "{{ maintenance_name }}"
            discord_operation: "Maintenance"
            discord_status: "failed"
            discord_detail: "check Semaphore logs"
            discord_color: "{{ discord_color_failure }}"
            discord_url: "{{ maintenance_url }}"

        - name: Log maintenance to MariaDB
          include_tasks: tasks/log_mariadb.yaml
          vars:
            log_table: "maintenance"
            log_application: "{{ maintenance_name }}"
            log_hostname: "{{ inventory_hostname }}"
            log_type: "{{ maintenance_type }}"
            log_subtype: "{{ maintenance_subtype }}"
            log_status: "{{ 'failed' if maintenance_failed else 'success' }}"
