---
# Restart Unifi Network services.
# Restarts the Unifi Network application service on the controller.
# Runs daily (not weekly) — Unifi Network has a known memory leak; daily restart
# keeps memory usage in check. This restarts only the controller service, not the
# network hardware, so there is no connectivity outage.

- name: Restart Unifi Network services
  hosts: "unifi_network"
  gather_facts: true
  gather_subset: ['!all', 'date_time']
  vars_files:
    - vars/secrets.yaml
    - vars/unifi_network.yaml
  vars:
    maintenance_name: "Unifi"
    maintenance_type: "Appliances"
    maintenance_subtype: "Restart"
    maintenance_description: "Restart Unifi Network service"

  pre_tasks:
    - name: Assert MariaDB logging database is reachable
      include_tasks: tasks/assert_db_connectivity.yaml

    - name: Log playbook run context to MariaDB
      include_tasks: tasks/log_run_context.yaml
      vars:
        log_playbook: "maintain_unifi.yaml"
        log_hostname: "{{ inventory_hostname }}"
        log_run_vars: "{}"

  tasks:
    - name: Initialize maintenance state
      ansible.builtin.set_fact:
        maintenance_failed: false

    - block:
        - name: Restart Unifi Network service
          become: true
          ansible.builtin.systemd:
            name: unifi
            state: restarted

      rescue:
        - name: Set maintenance failed
          ansible.builtin.set_fact:
            maintenance_failed: true

      always:
        - name: Send Discord alert on failure
          include_tasks: tasks/notify.yaml
          when: maintenance_failed
          vars:
            discord_name: "{{ maintenance_name }}"
            discord_operation: "Maintenance"
            discord_status: "failed"
            discord_detail: "check Semaphore logs"
            discord_color: "{{ discord_color_failure }}"
            discord_url: "{{ maintenance_url }}"

        - name: Log maintenance to MariaDB
          include_tasks: tasks/log_mariadb.yaml
          vars:
            log_table: "maintenance"
            log_application: "{{ maintenance_name }}"
            log_hostname: "{{ inventory_hostname }}"
            log_type: "{{ maintenance_type }}"
            log_subtype: "{{ maintenance_subtype }}"
            log_status: "{{ 'failed' if maintenance_failed else 'success' }}"
