---
# Clear Linux page cache on Ubuntu hosts.
# Drops page cache (echo 3 > /proc/sys/vm/drop_caches).
# Schedule with Semaphore to run weekly.

- name: Clear Linux page cache
  hosts: "ubuntu"
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
  vars:
    maintenance_name: "Ubuntu"
    maintenance_type: "Servers"
    maintenance_subtype: "Cache"
    maintenance_url: ""
    maintenance_description: "Drop Linux page cache (echo 3 > /proc/sys/vm/drop_caches)"
  pre_tasks:
    - name: Assert MariaDB logging database is reachable
      include_tasks: tasks/assert_db_connectivity.yaml

  tasks:
    - name: Initialize maintenance state
      ansible.builtin.set_fact:
        maintenance_failed: false

    - block:
        - name: Drop Linux page cache
          become: true
          ansible.builtin.shell: echo 3 > /proc/sys/vm/drop_caches
          changed_when: true

      rescue:
        - name: Set maintenance failed
          ansible.builtin.set_fact:
            maintenance_failed: true

      always:
        - name: Send Discord alert on failure
          include_tasks: tasks/notify_discord.yaml
          when: maintenance_failed
          vars:
            discord_title: "{{ maintenance_name }}"
            discord_description: "Maintenance Failed — check Semaphore logs for details"
            discord_color: 16711680
            discord_url: "{{ maintenance_url }}"
            discord_fields:
              - name: "Description"
                value: "{{ maintenance_description }}"
              - name: "Host"
                value: "{{ inventory_hostname }}"

        - name: Log maintenance to MariaDB
          include_tasks: tasks/log_mariadb.yaml
          vars:
            log_table: "maintenance"
            log_application: "{{ maintenance_name }}"
            log_hostname: "{{ inventory_hostname }}"
            log_type: "{{ maintenance_type }}"
            log_subtype: "{{ maintenance_subtype }}"
            log_status: "{{ 'failed' if maintenance_failed else 'success' }}"
