---
# Docker prune + page cache maintenance.
# Play 1: Prune unused Docker images and volumes across all Docker hosts.
#          Captures post-prune disk usage (images, volumes, containers) and logs
#          metrics to the docker_sizes table for Grafana trend monitoring.
# Play 2: Clear Linux page cache on Ubuntu and unRAID hosts.
# Schedule with Semaphore to run weekly.

- name: Prune unused Docker images
  hosts: "docker"
  gather_facts: true
  gather_subset: ['!all', 'date_time']
  vars_files:
    - vars/secrets.yaml
  vars:
    maintenance_name: "Docker"
    maintenance_type: "Servers"
    maintenance_subtype: "Prune"
    maintenance_url: ""
    maintenance_description: "Prune unused Docker images across all Docker hosts"

  pre_tasks:
    - name: Run standard pre-flight assertions
      include_tasks: tasks/pre_task_assertions.yaml
      vars:
        pre_playbook: "maintain_docker.yaml"

  tasks:
    - name: Initialize maintenance state
      ansible.builtin.set_fact:
        maintenance_failed: false

    - block:
        - name: Prune unused Docker images and volumes (Python SDK)
          become: true
          community.docker.docker_prune:
            images: true
            images_filters:
              dangling: "false"
            volumes: true
          when: inventory_hostname in groups["docker_stacks"] | default([])

        - name: Prune unused Docker images and volumes (shell fallback)
          become: true
          ansible.builtin.shell: docker system prune -af --volumes
          changed_when: true
          when: inventory_hostname not in groups["docker_stacks"] | default([])

        # docker system df default table output:
        #   TYPE            TOTAL  ACTIVE  SIZE    RECLAIMABLE
        #   Images          4      3       2.5GB   500MB (20%)
        #   Containers      3      3       100MB   0B (0%)
        #   Local Volumes   5      2       1.2GB   800MB (66%)
        # awk converts SIZE to MB (GB*1000, kB/1000) — one value per line
        - name: Capture Docker disk usage
          become: true
          ansible.builtin.shell: |
            docker system df 2>/dev/null | awk '
            function to_mb(s,   n) {
              n = s + 0
              if (s ~ /GB$/) return n * 1000
              if (s ~ /MB$/) return n
              if (s ~ /kB$/) return n / 1000
              return 0
            }
            /^Images /       { ic = $2; im = to_mb($4) }
            /^Containers /   { cm = to_mb($4) }
            /^Local Volumes / { vc = $3; vm = to_mb($5) }
            END { print ic; print im; print vc; print vm; print cm }'
          register: _docker_df
          changed_when: false

        - name: Parse Docker disk usage metrics
          ansible.builtin.set_fact:
            _docker_images_count:  "{{ _docker_df.stdout_lines[0] | int }}"
            _docker_images_mb:     "{{ _docker_df.stdout_lines[1] | float | round(2) }}"
            _docker_volumes_count: "{{ _docker_df.stdout_lines[2] | int }}"
            _docker_volumes_mb:    "{{ _docker_df.stdout_lines[3] | float | round(2) }}"
            _docker_containers_mb: "{{ _docker_df.stdout_lines[4] | float | round(2) }}"
          when: _docker_df.stdout_lines | length >= 5

      rescue:
        - name: Set maintenance failed
          ansible.builtin.set_fact:
            maintenance_failed: true

      always:
        - name: Send alert on failure
          include_tasks: tasks/notify.yaml
          when: maintenance_failed
          vars:
            discord_name: "{{ maintenance_name }}"
            discord_operation: "Maintenance"
            discord_status: "failed"
            discord_detail: "check Semaphore logs"
            discord_color: "{{ discord_color_failure }}"
            discord_url: "{{ maintenance_url }}"

        - name: Log maintenance to MariaDB
          include_tasks: tasks/log_mariadb.yaml
          vars:
            log_table: maintenance
            log_application: "{{ maintenance_name }}"
            log_hostname: "{{ inventory_hostname }}"
            log_type: "{{ maintenance_type }}"
            log_subtype: "{{ maintenance_subtype }}"
            log_status: "{{ 'failed' if maintenance_failed else 'success' }}"

        - name: Log Docker disk usage to MariaDB
          include_tasks: tasks/log_mariadb.yaml
          when: _docker_df is defined and not _docker_df.skipped | default(false)
          vars:
            log_table: docker_sizes
            log_hostname: "{{ inventory_hostname }}"
            log_images_count:  "{{ _docker_images_count | default(0) }}"
            log_images_mb:     "{{ _docker_images_mb | default(0) }}"
            log_volumes_count: "{{ _docker_volumes_count | default(0) }}"
            log_volumes_mb:    "{{ _docker_volumes_mb | default(0) }}"
            log_containers_mb: "{{ _docker_containers_mb | default(0) }}"

# ═══════════════════════════════════════════════════════════════════
# Play 2 — Clear Linux page cache
# ═══════════════════════════════════════════════════════════════════
- name: Clear Linux page cache
  hosts: "ubuntu:unraid"
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
  vars:
    maintenance_name: "{{ 'unRAID' if 'unraid' in group_names else 'Ubuntu' }}"
    maintenance_type: "Servers"
    maintenance_subtype: "Cache"
    maintenance_url: ""
    maintenance_description: "Drop Linux page cache (echo 3 > /proc/sys/vm/drop_caches)"

  pre_tasks:
    - name: Run standard pre-flight assertions
      include_tasks: tasks/pre_task_assertions.yaml
      vars:
        pre_playbook: "maintain_docker.yaml"

  tasks:
    - name: Initialize maintenance state
      ansible.builtin.set_fact:
        maintenance_failed: false

    - block:
        - name: Drop Linux page cache
          become: true
          ansible.builtin.shell: echo 3 > /proc/sys/vm/drop_caches
          changed_when: true

      rescue:
        - name: Set maintenance failed
          ansible.builtin.set_fact:
            maintenance_failed: true

      always:
        - name: Send alert on failure
          include_tasks: tasks/notify.yaml
          when: maintenance_failed
          vars:
            discord_name: "{{ maintenance_name }}"
            discord_operation: "Maintenance"
            discord_status: "failed"
            discord_detail: "check Semaphore logs"
            discord_color: "{{ discord_color_failure }}"
            discord_url: "{{ maintenance_url }}"

        - name: Log maintenance to MariaDB
          include_tasks: tasks/log_mariadb.yaml
          vars:
            log_table: maintenance
            log_application: "{{ maintenance_name }}"
            log_hostname: "{{ inventory_hostname }}"
            log_type: "{{ maintenance_type }}"
            log_subtype: "{{ maintenance_subtype }}"
            log_status: "{{ 'failed' if maintenance_failed else 'success' }}"
