---
# One-shot migration of /opt appdata from local RBD disk to CephFS shared storage.
# Stops all Docker stacks, rsyncs /opt to CephFS, remounts /opt from CephFS, restarts stacks.
# A Proxmox snapshot is taken before migration — on failure the VM is reverted to pre-migration state.
# Local /opt data is read-only during migration — safe to retry if migration fails after rsync.
#
# Required extra vars:
#   vm_name  — key in vm_definitions (e.g. tantiveiv, odyssey); must have cephfs_host_dir defined
#   confirm=yes — required safety gate
#
# Prerequisites (manual, on PVE cluster):
#   1. CephFS MDS deployed and active (ceph fs status cephfs)
#   2. CephFS filesystem created (cephfs_data + cephfs_metadata pools, ceph fs new cephfs ...)
#   3. client.vm-appdata auth key created (ceph auth get-or-create client.vm-appdata ...)
#   4. Per-host dir created on CephFS root (mkdir /mnt/cephfs_admin/<cephfs_host_dir>)
#   5. vault_ceph_mons and vault_ceph_vm_appdata_key added to vars/secrets.yaml

# ═══════════════════════════════════════════════════════════════════
# Play 1 — Validate and resolve migration parameters
# ═══════════════════════════════════════════════════════════════════
- name: Validate migration parameters
  hosts: localhost
  gather_facts: true
  gather_subset: ['!all', 'date_time']
  vars_files:
    - vars/secrets.yaml
    - vars/vm_definitions.yaml
    - vars/semaphore_check.yaml

  pre_tasks:
    - name: Assert required vars and safety gate
      ansible.builtin.assert:
        that:
          - vm_name is defined
          - vm_name in vm_definitions
          - confirm | default('no') == 'yes'
        fail_msg: >-
          Missing required vars or safety gate not set.
          Usage: -e vm_name=<key> -e confirm=yes
          Valid vm_name values: {{ vm_definitions.keys() | list | join(', ') }}

    - name: Assert vm has cephfs_host_dir defined
      ansible.builtin.assert:
        that:
          - vm_definitions[vm_name].cephfs_host_dir is defined
        fail_msg: >-
          {{ vm_name }} does not have cephfs_host_dir defined in vm_definitions.
          Only tantiveiv and odyssey support CephFS migration.

    - name: Assert MariaDB logging database is reachable
      include_tasks: tasks/assert_db_connectivity.yaml

    - name: Log playbook run context to MariaDB
      include_tasks: tasks/log_run_context.yaml
      vars:
        log_playbook: "migrate_appdata_to_cephfs.yaml"
        log_hostname: "{{ controller_fqdn }}"
        log_run_vars: "{{ {'vm_name': vm_name} | to_json | to_json }}"

  tasks:
    - name: Resolve migration parameters
      ansible.builtin.set_fact:
        _cephfs_host_dir: "{{ vm_definitions[vm_name].cephfs_host_dir }}"
        _migration_hostname: "{{ vm_definitions[vm_name].vm_hostname }}"

    - name: Add migration target to dynamic inventory
      ansible.builtin.add_host:
        name: "{{ _migration_hostname }}"
        ansible_host: "{{ vm_definitions[vm_name].vm_ip }}"
        groups:
          - migration_target
          - docker_stacks

    # ===== CREATE PRE-MIGRATION SNAPSHOT =====
    - name: Resolve VM actual node via cluster API
      ansible.builtin.uri:
        url: "https://{{ pve_api_host }}:8006/api2/json/cluster/resources?type=vm"
        method: GET
        headers:
          Authorization: "PVEAPIToken={{ pve_api_user }}!{{ pve_api_token_id }}={{ pve_api_token_secret }}"
        validate_certs: false
      register: _cluster_vms
      no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"

    - name: Set VM actual node
      ansible.builtin.set_fact:
        _vm_actual_node: >-
          {{ (_cluster_vms.json.data | selectattr('vmid', 'equalto', vm_definitions[vm_name].vm_id | int) | list | first).node }}

    - name: Get existing snapshots
      ansible.builtin.uri:
        url: "https://{{ pve_api_host }}:8006/api2/json/nodes/{{ _vm_actual_node }}/qemu/{{ vm_definitions[vm_name].vm_id }}/snapshot"
        method: GET
        headers:
          Authorization: "PVEAPIToken={{ pve_api_user }}!{{ pve_api_token_id }}={{ pve_api_token_secret }}"
        validate_certs: false
      register: _vm_snapshots
      no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"

    - name: Delete existing pre-migration snapshot if present
      ansible.builtin.uri:
        url: "https://{{ pve_api_host }}:8006/api2/json/nodes/{{ _vm_actual_node }}/qemu/{{ vm_definitions[vm_name].vm_id }}/snapshot/pre-cephfs-migration"
        method: DELETE
        headers:
          Authorization: "PVEAPIToken={{ pve_api_user }}!{{ pve_api_token_id }}={{ pve_api_token_secret }}"
        validate_certs: false
      no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"
      when: _vm_snapshots.json.data | selectattr('name', 'equalto', 'pre-cephfs-migration') | list | length > 0

    - name: Wait for VM lock to clear after snapshot delete
      ansible.builtin.uri:
        url: "https://{{ pve_api_host }}:8006/api2/json/nodes/{{ _vm_actual_node }}/qemu/{{ vm_definitions[vm_name].vm_id }}/status/current"
        method: GET
        headers:
          Authorization: "PVEAPIToken={{ pve_api_user }}!{{ pve_api_token_id }}={{ pve_api_token_secret }}"
        validate_certs: false
      register: _vm_lock_status
      until: _vm_lock_status.json.data.lock is not defined
      retries: 20
      delay: 3
      no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"
      when: _vm_snapshots.json.data | selectattr('name', 'equalto', 'pre-cephfs-migration') | list | length > 0

    - name: Create pre-migration snapshot
      ansible.builtin.uri:
        url: "https://{{ pve_api_host }}:8006/api2/json/nodes/{{ _vm_actual_node }}/qemu/{{ vm_definitions[vm_name].vm_id }}/snapshot"
        method: POST
        headers:
          Authorization: "PVEAPIToken={{ pve_api_user }}!{{ pve_api_token_id }}={{ pve_api_token_secret }}"
        body_format: form-urlencoded
        body:
          snapname: pre-cephfs-migration
          description: "Pre-CephFS migration — auto-created by migrate_appdata_to_cephfs.yaml"
          vmstate: 0
        validate_certs: false
      no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"

# ═══════════════════════════════════════════════════════════════════
# Play 2 — Migrate /opt to CephFS on the target VM
# ═══════════════════════════════════════════════════════════════════
- name: Migrate /opt appdata to CephFS
  hosts: migration_target
  become: true
  gather_facts: true
  vars_files:
    - vars/secrets.yaml
    - vars/vm_definitions.yaml
    - vars/docker_stacks.yaml
    - vars/semaphore_check.yaml

  tasks:
    - name: Initialize migration state
      ansible.builtin.set_fact:
        migration_failed: false
        _migration_detail: ""

    - block:
        # ─── Pre-flight check ───────────────────────────────────────
        - name: Check if /opt is already a CephFS mount
          ansible.builtin.command: findmnt -t ceph /opt
          register: _cephfs_check
          changed_when: false
          failed_when: false

        - name: Fail if /opt is already mounted as CephFS
          ansible.builtin.fail:
            msg: "/opt is already mounted as CephFS — run findmnt -t ceph /opt to inspect"
          when: _cephfs_check.rc == 0

        # ─── Install ceph-common and write keyring ──────────────────
        - name: Install ceph-common
          ansible.builtin.apt:
            name: ceph-common
            state: present

        - name: Write CephFS client keyring (INI format — for ceph CLI tools)
          ansible.builtin.copy:
            content: |
              [client.{{ cephfs_client_name }}]
                  key = {{ vault_ceph_vm_appdata_key }}
            dest: "{{ cephfs_keyring_path }}"
            owner: root
            group: root
            mode: "0600"

        - name: Write CephFS mount secret (raw key — for kernel secretfile= option)
          ansible.builtin.copy:
            content: "{{ vault_ceph_vm_appdata_key }}"
            dest: "{{ cephfs_keyring_path | regex_replace('\\.keyring$', '.secret') }}"
            owner: root
            group: root
            mode: "0600"

        - name: Write minimal ceph.conf (suppresses DNS SRV fallback warning)
          ansible.builtin.copy:
            content: |
              [global]
              mon_host = {{ vault_ceph_mons }}
            dest: /etc/ceph/ceph.conf
            owner: root
            group: root
            mode: "0644"

        # ─── Mount CephFS at staging path ──────────────────────────
        - name: Create staging mount directory
          ansible.builtin.file:
            path: /mnt/cephfs_migrate
            state: directory
            mode: "0755"

        - name: Mount CephFS at /mnt/cephfs_migrate (staging)
          ansible.posix.mount:
            path: /mnt/cephfs_migrate
            src: "{{ vault_ceph_mons }}:/{{ hostvars['localhost']._cephfs_host_dir }}"
            fstype: ceph
            opts: "name={{ cephfs_client_name }},secretfile={{ cephfs_keyring_path | regex_replace('\\.keyring$', '.secret') }},_netdev,x-systemd.requires=network-online.target"
            state: mounted

        # ─── Stop all Docker stacks ─────────────────────────────────
        - name: Stop all Docker stacks
          include_tasks: tasks/docker_stop.yaml

        # ─── Rsync /opt → CephFS ────────────────────────────────────
        - name: Sync /opt to CephFS (this may take several minutes for large datasets)
          ansible.builtin.command: rsync -av --delete /opt/ /mnt/cephfs_migrate/
          changed_when: true
          timeout: 3600

        # ─── Spot-check CephFS contents ─────────────────────────────
        - name: Check stacks directory exists on CephFS
          ansible.builtin.stat:
            path: /mnt/cephfs_migrate/stacks
          register: _cephfs_stacks_dir

        - name: Assert spot-check passed
          ansible.builtin.assert:
            that: _cephfs_stacks_dir.stat.exists and _cephfs_stacks_dir.stat.isdir
            fail_msg: "/mnt/cephfs_migrate/stacks not found after rsync — aborting before remount"

        # ─── Switch /opt to CephFS ──────────────────────────────────
        - name: Remove staging mount from fstab and unmount
          ansible.posix.mount:
            path: /mnt/cephfs_migrate
            state: absent

        - name: Mount CephFS at /opt (production)
          ansible.posix.mount:
            path: /opt
            src: "{{ vault_ceph_mons }}:/{{ hostvars['localhost']._cephfs_host_dir }}"
            fstype: ceph
            opts: "name={{ cephfs_client_name }},secretfile={{ cephfs_keyring_path | regex_replace('\\.keyring$', '.secret') }},_netdev,x-systemd.requires=network-online.target"
            state: mounted

        # ─── Restart all Docker stacks ──────────────────────────────
        - name: Start all Docker stacks
          include_tasks: tasks/docker_start.yaml

        # ─── Health check ────────────────────────────────────────────
        - name: Wait for containers to settle
          ansible.builtin.pause:
            seconds: 20

        - name: List running containers
          ansible.builtin.command: docker ps --format "table {% raw %}{{.Names}}\t{{.Status}}{% endraw %}"
          register: _docker_ps
          changed_when: false

        - name: Show running containers
          ansible.builtin.debug:
            msg: "{{ _docker_ps.stdout_lines }}"

        - name: Record migration detail
          ansible.builtin.set_fact:
            _migration_detail: >-
              /opt migrated to CephFS:/{{ hostvars['localhost']._cephfs_host_dir }} —
              {{ stack_assignments[inventory_hostname] | default([]) | join(', ') }} stacks restarted

      rescue:
        - name: Set migration failed flag
          ansible.builtin.set_fact:
            migration_failed: true
            _migration_detail: "{{ ansible_failed_result.msg | default('check Semaphore logs') }}"

# ═══════════════════════════════════════════════════════════════════
# Play 3 — Rollback or clean up pre-migration snapshot
# ═══════════════════════════════════════════════════════════════════
- name: Manage pre-migration snapshot
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
    - vars/vm_definitions.yaml

  tasks:
    - name: Resolve migration result
      ansible.builtin.set_fact:
        _snap_mig_failed: "{{ hostvars[_migration_hostname].migration_failed | default(true) }}"

    # ─── ROLLBACK on failure ────────────────────────────────────────
    - name: Rollback — stop VM
      community.general.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
        node: "{{ _vm_actual_node }}"
        vmid: "{{ vm_definitions[vm_name].vm_id }}"
        state: stopped
        force: true
      no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"
      when: _snap_mig_failed | bool

    - name: Rollback — revert to pre-migration snapshot
      ansible.builtin.uri:
        url: "https://{{ pve_api_host }}:8006/api2/json/nodes/{{ _vm_actual_node }}/qemu/{{ vm_definitions[vm_name].vm_id }}/snapshot/pre-cephfs-migration/rollback"
        method: POST
        headers:
          Authorization: "PVEAPIToken={{ pve_api_user }}!{{ pve_api_token_id }}={{ pve_api_token_secret }}"
        validate_certs: false
      no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"
      when: _snap_mig_failed | bool

    - name: Rollback — wait for snapshot revert
      ansible.builtin.pause:
        seconds: 20
      when: _snap_mig_failed | bool

    - name: Rollback — start VM after revert
      ansible.builtin.uri:
        url: "https://{{ pve_api_host }}:8006/api2/json/nodes/{{ _vm_actual_node }}/qemu/{{ vm_definitions[vm_name].vm_id }}/status/start"
        method: POST
        headers:
          Authorization: "PVEAPIToken={{ pve_api_user }}!{{ pve_api_token_id }}={{ pve_api_token_secret }}"
        validate_certs: false
      no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"
      when: _snap_mig_failed | bool

    - name: Rollback — wait for SSH
      ansible.builtin.wait_for:
        host: "{{ vm_definitions[vm_name].vm_ip }}"
        port: 22
        delay: 10
        timeout: 300
      when: _snap_mig_failed | bool

    # ─── CLEANUP on success ─────────────────────────────────────────
    - name: Delete pre-migration snapshot after successful migration
      ansible.builtin.uri:
        url: "https://{{ pve_api_host }}:8006/api2/json/nodes/{{ _vm_actual_node }}/qemu/{{ vm_definitions[vm_name].vm_id }}/snapshot/pre-cephfs-migration"
        method: DELETE
        headers:
          Authorization: "PVEAPIToken={{ pve_api_user }}!{{ pve_api_token_id }}={{ pve_api_token_secret }}"
        validate_certs: false
      no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"
      when: not (_snap_mig_failed | bool)

# ═══════════════════════════════════════════════════════════════════
# Play 4 — Log to MariaDB and send Discord notification
# ═══════════════════════════════════════════════════════════════════
- name: Log and notify migration result
  hosts: localhost
  gather_facts: false
  # ansible_date_time inherited from Play 1 fact cache — no re-gather needed
  vars_files:
    - vars/secrets.yaml
    - vars/semaphore_check.yaml

  tasks:
    - name: Resolve migration result from host
      ansible.builtin.set_fact:
        _mig_failed: "{{ hostvars[_migration_hostname].migration_failed | default(true) }}"
        _mig_detail: "{{ hostvars[_migration_hostname]._migration_detail | default('Play 2 did not run') }}"

    - name: Log migration to MariaDB
      include_tasks: tasks/log_mariadb.yaml
      vars:
        log_table: maintenance
        log_application: "{{ vm_name }}"
        log_hostname: "{{ controller_fqdn }}"
        log_type: "Servers"
        log_subtype: "CephFS Migration"
        log_status: "{{ 'failed' if _mig_failed | bool else 'success' }}"

    - block:
        - name: Send Discord notification
          include_tasks: tasks/notify.yaml
          vars:
            discord_name: "CephFS Migration"
            discord_operation: "Migrate"
            discord_status: "{{ 'failed' if _mig_failed | bool else 'successful' }}"
            discord_color: "{{ discord_color_failure if _mig_failed | bool else discord_color_success }}"
            discord_url: "{{ semaphore_ext_url }}"
            discord_author: "{{ controller_fqdn }}"
            discord_fields:
              - name: "VM"
                value: "{{ vm_name }}"
                inline: true
              - name: "CephFS Dir"
                value: "{{ _cephfs_host_dir }}"
                inline: true
              - name: "Detail"
                value: "{{ _mig_detail }}"
      rescue:
        - ansible.builtin.fail:
            msg: "Discord notification failed. Re-run with -e debug_no_log=yes for details."

    - name: Fail play if migration failed
      ansible.builtin.fail:
        msg: "Migration failed: {{ _mig_detail }}"
      when: _mig_failed | bool
