---
# Rollback Docker containers to their previous image versions.
# Reads the rollback snapshot saved by update_systems.yaml and reverts
# containers using either local re-tag (fast) or registry pull (if pruned).
#
# Docker Compose hosts (docker_stacks group) only.
# For unRAID docker_run hosts, see DESIGN.md manual rollback guidance.
#
# Safety-gated: requires -e confirm=yes to proceed.
# Without it, shows snapshot info and exits (dry-run).
#
# Required variables (vars/secrets.yaml):
#   logging_db_host, logging_db_port, logging_db_user, logging_db_password, logging_db_name
#   discord_webhook_id, discord_webhook_token
#
# Scope selectors:
#   stack=<name>            — rollback a single stack (auto-resolves host)
#   app=<name>              — rollback a single app's stack (resolves via app_definitions)
#   rollback_stack=<name>   — alias for stack (backward compatibility)
#   rollback_service=<name> — rollback a single service within a stack
#   role=<name>             — rollback all stacks in a role (auto-resolves host)
#
# Options:
#   with_backup=yes         — also restore appdata from backup + auto-detect DB dependencies
#
# Usage:
#   # Rollback all containers (image-only, fast)
#   ansible-playbook rollback_docker.yaml -e hosts_variable=docker_stacks \
#     --limit <hostname> -e confirm=yes
#
#   # Rollback one stack (image-only)
#   ansible-playbook rollback_docker.yaml -e hosts_variable=docker_stacks \
#     -e stack=auth -e confirm=yes
#
#   # Rollback one stack — images + appdata + auto-detected DB restore
#   ansible-playbook rollback_docker.yaml -e hosts_variable=docker_stacks \
#     -e stack=auth -e with_backup=yes -e confirm=yes
#
#   # Rollback all stacks in a role — images + appdata + DB
#   ansible-playbook rollback_docker.yaml -e hosts_variable=docker_stacks \
#     -e role=core -e with_backup=yes -e confirm=yes
#
#   # Rollback one service (image-only)
#   ansible-playbook rollback_docker.yaml -e hosts_variable=docker_stacks \
#     --limit <hostname> -e rollback_service=jellyseerr -e confirm=yes
#
#   # Dry run — show snapshot info without rolling back
#   ansible-playbook rollback_docker.yaml -e hosts_variable=docker_stacks \
#     --limit <hostname>

- name: Rollback — Docker Containers
  hosts: "{{ hosts_variable }}"
  serial: 1
  gather_facts: true
  vars_files:
    - vars/secrets.yaml
    - vars/vm_definitions.yaml
    - vars/host_definitions.yaml
    - vars/app_definitions.yaml
    - "vars/{{ config_file }}.yaml"
  vars:
    config_file: "{{ hosts_variable }}"

  pre_tasks:
    - name: Resolve rollback_stack → stack alias
      ansible.builtin.set_fact:
        stack: "{{ rollback_stack }}"
      when:
        - rollback_stack is defined
        - stack is not defined

    - name: Resolve scope (role injection + stack/role filtering)
      include_tasks: tasks/resolve_scope.yaml


    - name: Run standard pre-flight assertions
      include_tasks: tasks/pre_task_assertions.yaml
      vars:
        pre_assert_config_file: true
        pre_playbook: "rollback_docker.yaml"

    - name: Assert Docker Compose host
      ansible.builtin.assert:
        that: inventory_hostname in groups["docker_stacks"] | default([])
        fail_msg: "Rollback only supports docker_stacks hosts. For docker_run (unRAID), see DESIGN.md manual rollback section."

    # Stack mode: read and merge per-stack snapshots
    - name: Read rollback snapshots (stack mode)
      become: true
      ansible.builtin.slurp:
        src: "/opt/stacks/{{ item }}/.rollback_snapshot.json"
      loop: "{{ stack_assignments[inventory_hostname] | default([]) }}"
      register: _snapshot_stacks_raw
      check_mode: false
      when: inventory_hostname in (stack_assignments | default({}))
      ignore_errors: true

    - name: Merge stack snapshots and build service map (stack mode)
      ansible.builtin.set_fact:
        rollback_snapshot: >-
          {{ rollback_snapshot | default({'timestamp': '', 'containers': {}})
             | combine({
                 'timestamp': [
                   (rollback_snapshot | default({'timestamp': ''})).timestamp,
                   (item.content | b64decode | from_json).timestamp
                 ] | max,
                 'containers': (rollback_snapshot | default({'containers': {}})).containers
                               | combine((item.content | b64decode | from_json).containers)
               }) }}
        _service_stack_map: >-
          {{ _service_stack_map | default({})
             | combine(dict(
                 (item.content | b64decode | from_json).containers.keys() | list
                 | zip(
                   (item.content | b64decode | from_json).containers.keys()
                   | map('regex_replace', '.+', item.item) | list
                 ))) }}
      loop: "{{ _snapshot_stacks_raw.results | default([]) | selectattr('content', 'defined') | list }}"
      when: inventory_hostname in (stack_assignments | default({}))

    - name: Assert rollback snapshot exists
      ansible.builtin.assert:
        that: rollback_snapshot is defined and rollback_snapshot.containers | length > 0
        fail_msg: >
          No rollback snapshot found. Run Update — Docker Stacks [Containers] first
          to create a snapshot before attempting rollback.

    - name: Show snapshot info
      ansible.builtin.debug:
        msg: "Snapshot from {{ rollback_snapshot.timestamp }} — {{ rollback_snapshot.containers | length }} containers: {{ rollback_snapshot.containers.keys() | join(', ') }}"

    - name: Determine rollback targets
      ansible.builtin.set_fact:
        _rollback_targets: >-
          {{ [rollback_service] if rollback_service is defined
             else (rollback_snapshot.containers.keys() | list
                   | select('in', (_service_stack_map | default({}) | dict2items
                                   | selectattr('value', 'eq', stack)
                                   | map(attribute='key') | list))
                   | list) if stack is defined
             else rollback_snapshot.containers.keys() | list }}

    - name: Assert requested service exists in snapshot
      ansible.builtin.assert:
        that: item in rollback_snapshot.containers
        fail_msg: "Service '{{ item }}' not found in snapshot. Available: {{ rollback_snapshot.containers.keys() | join(', ') }}"
      loop: "{{ _rollback_targets }}"

    - name: Determine target stacks from rollback targets
      ansible.builtin.set_fact:
        _rollback_target_stacks: >-
          {{ _rollback_targets
             | map('extract', _service_stack_map | default({}))
             | select('defined') | unique | list }}

    - name: Assert confirm for destructive operation
      ansible.builtin.assert:
        that: confirm | default('') == 'yes'
        fail_msg: >
          Safety gate: pass -e confirm=yes to proceed.
          Omit it to dry-run (shows snapshot contents without rolling back).
      when: not ansible_check_mode

  tasks:
    - name: Initialize rollback state
      ansible.builtin.set_fact:
        rollback_failed: false
        _rollback_detail: ""

    - block:
        # ═══════════════════════════════════════════════════════════════════
        # WITH_BACKUP — stop stacks, restore appdata + DBs, then rollback
        # ═══════════════════════════════════════════════════════════════════
        - name: Stop target stacks for backup restore
          include_tasks: tasks/docker_stop.yaml
          vars:
            _docker_selective_stacks: "{{ _rollback_target_stacks }}"
          when:
            - with_backup | default('') == 'yes'
            - not ansible_check_mode

        - name: Find and restore appdata per stack
          include_tasks: tasks/rollback_restore_stack.yaml
          loop: "{{ _rollback_target_stacks }}"
          loop_control:
            loop_var: _rollback_stack
          when: with_backup | default('') == 'yes'

        - name: Auto-detect DB dependencies from app_definitions
          ansible.builtin.set_fact:
            _rollback_db_deps: >-
              {{ app_definitions | default({}) | dict2items
                 | selectattr('value.stack', 'in', _rollback_target_stacks)
                 | selectattr('value.db_names', 'defined')
                 | list }}
          when: with_backup | default('') == 'yes'

        - name: Start database containers for DB restore
          include_tasks: tasks/docker_start.yaml
          vars:
            _docker_selective_stacks: ["databases"]
          when:
            - with_backup | default('') == 'yes'
            - _rollback_db_deps | default([]) | length > 0
            - "'databases' in _rollback_target_stacks"
            - not ansible_check_mode

        - name: Restore auto-detected DB dumps
          include_tasks: tasks/rollback_restore_dbs.yaml
          loop: "{{ _rollback_db_deps | default([]) }}"
          loop_control:
            loop_var: _db_dep
          when:
            - with_backup | default('') == 'yes'
            - _rollback_db_deps | default([]) | length > 0
            - not ansible_check_mode

        # ═══════════════════════════════════════════════════════════════════
        # IMAGE ROLLBACK — re-tag or pull old images
        # ═══════════════════════════════════════════════════════════════════
        - include_tasks: tasks/rollback_images.yaml

        # ═══════════════════════════════════════════════════════════════════
        # RECREATE — bring containers back with old images
        # ═══════════════════════════════════════════════════════════════════
        - name: Recreate containers with old images
          become: true
          ansible.builtin.shell: >
            docker compose up -d
            {{ '' if (with_backup | default('') == 'yes') else
               (_rollback_targets
                | select('in', (_service_stack_map | default({}) | dict2items
                                | selectattr('value', 'eq', item)
                                | map(attribute='key') | list))
                | join(' ')) }}
          args:
            chdir: "/opt/stacks/{{ item }}"
          loop: "{{ _rollback_target_stacks }}"
          when: inventory_hostname in (stack_assignments | default({}))

        - name: Wait for containers to stabilize
          ansible.builtin.pause:
            seconds: 10

        - name: Verify containers are running
          become: true
          ansible.builtin.shell: >
            docker compose ps --format json {{ item }}
          args:
            chdir: "/opt/stacks/{{ _service_stack_map[item] }}"
          loop: "{{ _rollback_targets }}"
          register: _container_status
          changed_when: false
          when: inventory_hostname in (stack_assignments | default({}))

        - name: Record rollback detail
          ansible.builtin.set_fact:
            _rollback_detail: >-
              Rolled back {{ _rollback_targets | length }} container(s) to snapshot from {{ rollback_snapshot.timestamp }}.
              {{ _rollback_image_detail | default('') }}{{ '. Appdata + DB restored from backup.' if (with_backup | default('') == 'yes') else '' }}

      rescue:
        - name: Set rollback failed flag
          ansible.builtin.set_fact:
            rollback_failed: true
            _rollback_detail: "Error: {{ ansible_failed_result.msg | default('unknown') }}"

        - name: Attempt to restart stacks after failure
          include_tasks: tasks/docker_start.yaml
          vars:
            _docker_selective_stacks: "{{ _rollback_target_stacks }}"
            _docker_ignore_errors: true
          when: with_backup | default('') == 'yes'

      always:
        - name: Send Discord notification
          include_tasks: tasks/notify.yaml
          vars:
            discord_name: "{{ update_name | default('Docker') }}"
            discord_operation: "Rollback"
            discord_status: "{{ 'failed' if rollback_failed else 'successful' }}"
            discord_color: "{{ discord_color_failure if rollback_failed else discord_color_rollback }}"
            discord_url: "{{ backup_url }}"
            discord_fields:
              - name: "Services"
                value: "{{ _rollback_targets | join(', ') }}"
              - name: "Snapshot Date"
                value: "{{ rollback_snapshot.timestamp }}"
              - name: "Detail"
                value: "{{ _rollback_detail | default('') }}"

        - name: Log rollback to MariaDB
          include_tasks: tasks/log_restore.yaml
          loop: "{{ _rollback_targets }}"
          vars:
            log_hostname: "{{ inventory_hostname }}"
            restore_application: "{{ item }}"
            restore_source_file: ".rollback_snapshot.json"
            restore_type: "Servers"
            restore_subtype: "Container"
            restore_operation: "rollback"
            restore_status: "{{ 'failed' if rollback_failed else 'success' }}"
            restore_detail: "Rolled back to snapshot from {{ rollback_snapshot.timestamp }}"

        - name: Fail play if rollback errored
          ansible.builtin.fail:
            msg: "Docker rollback failed — see Discord notification for details"
          when: rollback_failed
