---
# One-time setup for test VM VLAN isolation on Unifi UDM.
# Creates test-isolation VLAN network (idempotent). Prints zone policy settings for manual creation.
# Safe to re-run — skips the VLAN if it already exists.
#
# PREREQUISITE (manual, one-time — too risky to automate):
#   Add vault_test_vlan_id to the Proxmox uplink port profile in Unifi UI before running:
#     Devices → Switch → Ports → click a Proxmox uplink port → note profile name
#     Settings → Profiles → Port Profiles → <profile> → Tagged Networks → add VLAN
#   Save — additive change, no outage.
#   Record the profile name as vault_pve_port_profile_name in vault.
#
# Usage:
#   ansible-playbook setup_test_network.yaml --vault-password-file ~/.vault_pass
#   ansible-playbook setup_test_network.yaml --check --vault-password-file ~/.vault_pass
#     --check — runs all GETs and prereq checks, skips all writes, prints what would change
#
# Firewall zone policies (Step 2 — manual):
#   Unifi Network in zone-based firewall mode does not support automated policy creation.
#   The classic /rest/firewallrule POST endpoint is blocked in zone-based mode.
#   This playbook prints the exact zone policy settings to enter in Unifi UI.
#   Create both policies manually, then re-run — it will confirm the VLAN is present.
#
# Required vault vars:
#   vault_test_vlan_id           — VLAN ID (e.g. 3)
#   vault_test_vlan_gateway      — gateway IP on test VLAN (e.g. 192.168.3.1)
#   vault_test_vlan_subnet       — network CIDR (e.g. 192.168.3.0/24)
#   vault_pve_port_profile_name  — Unifi switch port profile used by Proxmox uplinks
#   unifi_network_api_key        — Unifi Network API key (already in vault)
#
# Derived (no additional vault vars needed):
#   Semaphore IP   — extracted from semaphore_host_url (already in vault)
#   Prod LAN CIDR  — derived from vault_vm_gateway + vm_cidr (already in vault)

- name: Setup test VM network isolation on Unifi
  hosts: unifi_network
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
    - vars/vm_definitions.yaml
    - vars/semaphore_check.yaml
  vars:
    _unifi_api: "https://{{ inventory_hostname }}/proxy/network/api/s/default"
    _semaphore_ip: "{{ semaphore_host_url | urlsplit('hostname') }}"
    _prod_lan_subnet: "{{ vault_vm_gateway | regex_replace('(\\d+\\.\\d+\\.\\d+)\\.\\d+', '\\1.0') }}/{{ vm_cidr }}"
    _ssh_policy_name: "Allow Server to Test"
    _ceph_policy_name: "Allow Test to Ceph"
    _block_policy_name: "Block Test to Internal"

  tasks:
    # ═══════════════════════════════════════════════════════════
    # STEP 0 — Prereq check: VLAN must already be in port profile
    # ═══════════════════════════════════════════════════════════
    - name: Get Unifi port profiles
      ansible.builtin.uri:
        url: "{{ _unifi_api }}/rest/portconf"
        method: GET
        headers:
          x-api-key: "{{ unifi_network_api_key }}"
        validate_certs: false
      register: _portconf
      check_mode: false
      no_log: "{{ not (debug_no_log | default(false) | bool) }}"

    - name: Find Proxmox uplink port profile
      ansible.builtin.set_fact:
        _pve_profile: >-
          {{ _portconf.json.data
             | selectattr('name', 'equalto', vault_pve_port_profile_name)
             | list | first | default({}) }}

    - name: Assert port profile exists
      ansible.builtin.assert:
        that: _pve_profile | length > 0
        fail_msg: >-
          Port profile '{{ vault_pve_port_profile_name }}' not found in Unifi.
          Check vault_pve_port_profile_name matches the profile name exactly.

    - name: Get all Unifi networks
      ansible.builtin.uri:
        url: "{{ _unifi_api }}/rest/networkconf"
        method: GET
        headers:
          x-api-key: "{{ unifi_network_api_key }}"
        validate_certs: false
      register: _all_networks
      check_mode: false
      no_log: "{{ not (debug_no_log | default(false) | bool) }}"

    - name: Find test VLAN network _id
      ansible.builtin.set_fact:
        _test_vlan_net_id: >-
          {{ (_all_networks.json.data
             | selectattr('vlan', 'defined')
             | selectattr('vlan', 'equalto', vault_test_vlan_id | int)
             | list | first | default({})).get('_id', '') }}

    - name: Assert VLAN network exists and is not excluded from port profile
      ansible.builtin.assert:
        that:
          - _test_vlan_net_id | length > 0
          - _test_vlan_net_id not in (_pve_profile.excluded_networkconf_ids | default([]))
        fail_msg: >-
          VLAN {{ vault_test_vlan_id }} is not tagged on port profile '{{ vault_pve_port_profile_name }}'.
          Add it manually in Unifi UI first:
            Settings → Profiles → Port Profiles → {{ vault_pve_port_profile_name }}
            → Tagged Networks → add test-isolation (VLAN {{ vault_test_vlan_id }})
          Then re-run this playbook.

    # ═══════════════════════════════════════════════════════════
    # STEP 1 — Create test-isolation VLAN network (if missing)
    # ═══════════════════════════════════════════════════════════
    - name: Check if test-isolation VLAN already exists
      ansible.builtin.set_fact:
        _test_vlan_exists: >-
          {{ _all_networks.json.data
             | selectattr('vlan', 'defined')
             | selectattr('vlan', 'equalto', vault_test_vlan_id | int)
             | list | length > 0 }}

    - name: Create test-isolation VLAN network
      ansible.builtin.uri:
        url: "{{ _unifi_api }}/rest/networkconf"
        method: POST
        headers:
          x-api-key: "{{ unifi_network_api_key }}"
        body_format: json
        body:
          name: "test-isolation"
          purpose: "corporate"
          vlan: "{{ vault_test_vlan_id | int }}"
          vlan_enabled: true
          ip_subnet: "{{ vault_test_vlan_gateway }}/24"
          dhcpd_enabled: false
          ipv6_interface_type: "none"
        validate_certs: false
        status_code: [200, 201]
      when: not _test_vlan_exists and not ansible_check_mode
      no_log: "{{ not (debug_no_log | default(false) | bool) }}"
      register: _create_vlan

    - name: Record VLAN status
      ansible.builtin.set_fact:
        _vlan_status: "{{ 'created' if not _test_vlan_exists else 'already existed' }}"

    # ═══════════════════════════════════════════════════════════
    # STEP 2 — Zone policies (manual — zone-based API not accessible)
    # NOTE: The classic /rest/firewallrule POST endpoint rejects all rule_index
    # values when Unifi Network is in zone-based firewall mode (GET returns empty,
    # POST returns FirewallRuleIndexOutOfRange for any 2xxx/4xxx index).
    # Policies must be created manually in the Unifi UI.
    # ═══════════════════════════════════════════════════════════
    - name: Print zone policy manual creation instructions
      ansible.builtin.debug:
        msg:
          - "═══ MANUAL ACTION REQUIRED — Zone Policies ═══"
          - "Unifi zone-based firewall mode requires manual policy creation."
          - "Go to: Settings → Firewall & Security → Rules → Create Policy"
          - ""
          - "Policy 1 — '{{ _ssh_policy_name }}'"
          - "  Source Zone: Server  |  Source IP: {{ _semaphore_ip }}/32"
          - "  Action: Allow"
          - "  Destination Zone: Guest  |  Destination Network: test-isolation  |  Port: 22  |  Protocol: TCP"
          - "  (Allows Semaphore to SSH into test VMs on the isolated VLAN)"
          - ""
          - "Policy 2 — '{{ _ceph_policy_name }}'  ← must be ABOVE the block rule"
          - "  Source Zone: Guest  |  Source Network: test-isolation"
          - "  Action: Allow"
          - "  Destination Zone: Server  |  Ports: 3300,6789,6800-7300  |  Protocol: TCP"
          - "  (Allows test VMs to mount CephFS — client connects to mon + OSD + MDS)"
          - ""
          - "Policy 3 — '{{ _block_policy_name }}'"
          - "  Source Zone: Guest  |  Source IP: {{ vault_test_vlan_subnet }}"
          - "  Action: Block"
          - "  Destination Zone: Any (all internal zones)"
          - "  (Blocks test VMs from reaching any other internal network)"
          - ""
          - "Policy order matters — evaluate top to bottom, first match wins:"
          - "  1. {{ _ssh_policy_name }}"
          - "  2. {{ _ceph_policy_name }}"
          - "  3. {{ _block_policy_name }}"
          - ""
          - "After creating all policies in order, re-run this playbook to verify the VLAN is present."
      when: not ansible_check_mode

    # ═══════════════════════════════════════════════════════════
    # CHECK MODE — Report
    # ═══════════════════════════════════════════════════════════
    - name: "[CHECK MODE] Report"
      ansible.builtin.debug:
        msg:
          - "=== CHECK MODE — No changes made ==="
          - "VLAN {{ vault_test_vlan_id }} (test-isolation): {{ 'would be created' if not _test_vlan_exists else 'already exists — no action needed' }}"
          - ""
          - "Zone policies require manual creation in Unifi UI (Settings → Firewall & Security → Rules → Create Policy):"
          - "  Policy 1 — '{{ _ssh_policy_name }}': Source=Server/{{ _semaphore_ip }}/32 → Allow → Dest=Guest/test-isolation:22/TCP"
          - "  Policy 2 — '{{ _ceph_policy_name }}': Source=Guest/test-isolation → Allow → Dest=Server:3300,6789,6800-7300/TCP"
          - "  Policy 3 — '{{ _block_policy_name }}': Source=Guest/{{ vault_test_vlan_subnet }} → Block → Dest=Any"
          - ""
          - "Re-run without --check after creating policies to verify."
      when: ansible_check_mode

    # ═══════════════════════════════════════════════════════════
    # STEP 3 — Verify VLAN exists; check if rules were manually created
    # ═══════════════════════════════════════════════════════════
    - name: Re-fetch networks for verification
      ansible.builtin.uri:
        url: "{{ _unifi_api }}/rest/networkconf"
        method: GET
        headers:
          x-api-key: "{{ unifi_network_api_key }}"
        validate_certs: false
      register: _verify_networks
      no_log: "{{ not (debug_no_log | default(false) | bool) }}"
      when: not ansible_check_mode

    - name: Assert test-isolation VLAN exists
      ansible.builtin.assert:
        that: >-
          _verify_networks.json.data
          | selectattr('vlan', 'defined')
          | selectattr('vlan', 'equalto', vault_test_vlan_id | int)
          | list | length > 0
        fail_msg: "test-isolation VLAN {{ vault_test_vlan_id }} not found"
      when: not ansible_check_mode

    - name: Print summary
      ansible.builtin.debug:
        msg:
          - "=== Test VLAN Setup Complete — Zone Policies Pending ==="
          - "VLAN {{ vault_test_vlan_id }} (test-isolation): {{ _vlan_status }}"
          - ""
          - "⚠ Zone policies must be created manually (see instructions above)."
          - "  After creating both policies in Unifi UI, re-run to confirm the VLAN is present."
          - ""
          - "Next steps after manual policy creation:"
          - "  1. Run build_ubuntu.yaml -e vm_name=test-vm to provision a test VM"
          - "  2. Verify: VLAN tag on net0 in Proxmox UI, IP in {{ vault_test_vlan_subnet }}"
          - "  3. From test VM: ping prod host → timeout; curl https://hub.docker.com → 200"
      when: not ansible_check_mode
