---
# Install and configure keepalived on all Proxmox nodes to provide a floating management VIP.
# The VIP is used as pve_api_host so VM provisioning works even if the primary node is down.
# The MASTER node (highest vault_pve_vrrp_priorities entry) normally holds the VIP.
# On MASTER failure, the next highest-priority BACKUP takes over within ~3 seconds.
#
# Usage (run once, re-run if config changes):
#   ansible-playbook setup_pve_vip.yaml
#
# Required vault vars (add to vars/secrets.yaml before running):
#   vault_pve_vip               — unused IP in 10.10.10.0/24 for the floating address
#   vault_pve_vrrp_password     — VRRP authentication passphrase (any string)
#   vault_pve_vrrp_priorities   — dict: inventory_hostname (FQDN) → integer priority
#                                   e.g. REDACTED_NODE.local: 150 / REDACTED_NODE.local: 100 / REDACTED_NODE.local: 50
#   vault_pve_template_node_ip  — direct IP of the MASTER node (REDACTED_NODE: REDACTED_IP)
#                                   used by provision_vm.yaml for SSH template creation
#
# After running:
#   1. Verify the VIP is up: ping <vault_pve_vip>
#   2. Update pve_api_host in secrets.yaml to vault_pve_vip
#   3. Check status on each node: ip addr show vmbr0 | grep <vault_pve_vip>
#   4. Test a VM build: ansible-playbook build_ubuntu.yaml -e vm_name=test-vm

- name: Configure keepalived VRRP VIP on Proxmox nodes
  hosts: pve
  become: true
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
    - vars/proxmox.yaml

  tasks:
    - name: Install keepalived
      ansible.builtin.apt:
        name: keepalived
        state: present
        update_cache: true

    - name: Template keepalived config
      ansible.builtin.template:
        src: templates/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: "0640"
      notify: Restart keepalived

    - name: Enable and start keepalived
      ansible.builtin.service:
        name: keepalived
        state: started
        enabled: true

  handlers:
    - name: Restart keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted
