---
# Install and configure keepalived on all Proxmox nodes to provide a floating management VIP.
# The VIP is used as pve_api_host so VM provisioning works even if the primary node is down.
# The MASTER node (highest vault_pve_vrrp_priorities entry) normally holds the VIP.
# On MASTER failure, the next highest-priority BACKUP takes over within ~3 seconds.
#
# Usage (run once, re-run if config changes):
#   ansible-playbook setup_pve_vip.yaml
#
# Required vault vars (add to vars/secrets.yaml before running):
#   vault_pve_vip               — unused IP in 10.10.10.0/24 for the floating address
#   vault_pve_vrrp_password     — VRRP authentication passphrase (any string)
#   vault_pve_vrrp_priorities   — dict: short node name → integer priority (domain from vault_vm_search_domain)
#                                   e.g. REDACTED_NODE: 150 / REDACTED_NODE: 100 / REDACTED_NODE: 50
#   vault_pve_template_node_ip  — direct IP of the MASTER node (REDACTED_NODE: REDACTED_IP)
#                                   used by provision_vm.yaml for SSH template creation
#
# After running:
#   1. Update pve_api_host in secrets.yaml to vault_pve_vip
#   2. Test a VM build: ansible-playbook build_ubuntu.yaml -e vm_name=test-vm

# ═══════════════════════════════════════════════════════════════════
# Play 1 — Install and configure keepalived on all PVE nodes
# ═══════════════════════════════════════════════════════════════════
- name: Configure keepalived VRRP VIP on Proxmox nodes
  hosts: pve
  become: true
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
    - vars/proxmox.yaml

  tasks:
    - name: Install keepalived
      ansible.builtin.apt:
        name: keepalived
        state: present
        update_cache: true

    - name: Template keepalived config
      ansible.builtin.template:
        src: templates/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: "0640"
      notify: Restart keepalived

    - name: Enable and start keepalived
      ansible.builtin.service:
        name: keepalived
        state: started
        enabled: true

    # ── Verification ──────────────────────────────────────────────
    - name: Flush handlers (restart keepalived if config changed)
      meta: flush_handlers

    - name: Wait for VRRP election to complete
      ansible.builtin.pause:
        seconds: 3
      run_once: true

    - name: Check VIP presence on {{ pve_vrrp_interface }}
      ansible.builtin.shell: "ip addr show {{ pve_vrrp_interface }} | grep -c '{{ vault_pve_vip }}' || true"
      register: _vip_present
      changed_when: false

    - name: Report keepalived role on each node
      ansible.builtin.debug:
        msg: >-
          {{ inventory_hostname }}: {{ 'MASTER — VIP ' + vault_pve_vip + ' is present on ' + pve_vrrp_interface
          if _vip_present.stdout | int > 0 else 'BACKUP — VIP not held (correct)' }}

  handlers:
    - name: Restart keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted

# ═══════════════════════════════════════════════════════════════════
# Play 2 — Verify VIP is reachable from the controller
# ═══════════════════════════════════════════════════════════════════
- name: Verify VIP is reachable
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
    - vars/proxmox.yaml

  tasks:
    - name: Wait for VIP to respond on port 22 (SSH via MASTER node)
      ansible.builtin.wait_for:
        host: "{{ vault_pve_vip }}"
        port: 22
        timeout: 15
        msg: "VIP {{ vault_pve_vip }} is not reachable on port 22 — keepalived may not have converged"

    - name: VIP is up
      ansible.builtin.debug:
        msg: "VIP {{ vault_pve_vip }} is reachable. keepalived is healthy."
