---
# One-time setup for test VM network isolation on Unifi UDM.
# Creates test-isolation VLAN network + two LAN_IN firewall rules.
# Idempotent — safe to re-run; skips resources that already exist.
#
# PREREQUISITE (manual, one-time — too risky to automate):
#   Add vault_test_vlan_id to the Proxmox uplink port profile in Unifi UI before running:
#     Devices → Switch → Ports → click a Proxmox uplink port → note profile name
#     Settings → Profiles → Port Profiles → <profile> → Tagged Networks → add VLAN
#   Save — additive change, no outage.
#   Record the profile name as vault_pve_port_profile_name in vault.
#
# Usage:
#   ansible-playbook setup_test_network.yaml --vault-password-file ~/.vault_pass
#   ansible-playbook setup_test_network.yaml --check --vault-password-file ~/.vault_pass
#     --check — runs all GETs and prereq checks, skips all writes, prints what would change
#
# Firewall rules (Step 2):
#   Automated rule creation is NOT supported when Unifi Network is in zone-based firewall mode.
#   The classic /rest/firewallrule POST endpoint rejects all rule_index values in that mode.
#   This playbook prints the exact rules to create manually in Unifi UI and verifies the VLAN.
#   After creating the rules manually, re-run this playbook — it will confirm the VLAN is present.
#
# Required vault vars:
#   vault_test_vlan_id           — VLAN ID (e.g. 3)
#   vault_test_vlan_gateway      — gateway IP on test VLAN (e.g. 192.168.3.1)
#   vault_test_vlan_subnet       — network CIDR (e.g. 192.168.3.0/24)
#   vault_pve_port_profile_name  — Unifi switch port profile used by Proxmox uplinks
#   unifi_network_api_key        — Unifi Network API key (already in vault)
#
# Derived (no additional vault vars needed):
#   Semaphore IP   — extracted from semaphore_host_url (already in vault)
#   Prod LAN CIDR  — derived from vault_vm_gateway + vm_cidr (already in vault)

- name: Setup test VM network isolation on Unifi
  hosts: unifi_network
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
    - vars/vm_definitions.yaml
    - vars/semaphore_check.yaml
  vars:
    _unifi_api: "https://{{ inventory_hostname }}/proxy/network/api/s/default"
    _semaphore_ip: "{{ semaphore_host_url | urlsplit('hostname') }}"
    _prod_lan_subnet: "{{ vault_vm_gateway | regex_replace('(\\d+\\.\\d+\\.\\d+)\\.\\d+', '\\1.0') }}/{{ vm_cidr }}"
    use_zone_rules: true
    _semaphore_zone_name: "Server"   # zone containing homedwellers_server (where Semaphore lives)
    _test_vlan_zone_name: "Guest"    # zone containing homedwellers_test; change to "Test" if you create a dedicated zone
    _ssh_rule_name: "Allow Server to Test"
    _block_rule_name: "Block Test to Server"

  tasks:
    # ═══════════════════════════════════════════════════════════
    # STEP 0 — Prereq check: VLAN must already be in port profile
    # ═══════════════════════════════════════════════════════════
    - name: Get Unifi port profiles
      ansible.builtin.uri:
        url: "{{ _unifi_api }}/rest/portconf"
        method: GET
        headers:
          x-api-key: "{{ unifi_network_api_key }}"
        validate_certs: false
      register: _portconf
      check_mode: false
      no_log: "{{ not (debug_no_log | default(false) | bool) }}"

    - name: Find Proxmox uplink port profile
      ansible.builtin.set_fact:
        _pve_profile: >-
          {{ _portconf.json.data
             | selectattr('name', 'equalto', vault_pve_port_profile_name)
             | list | first | default({}) }}

    - name: Assert port profile exists
      ansible.builtin.assert:
        that: _pve_profile | length > 0
        fail_msg: >-
          Port profile '{{ vault_pve_port_profile_name }}' not found in Unifi.
          Check vault_pve_port_profile_name matches the profile name exactly.

    - name: Get all Unifi networks
      ansible.builtin.uri:
        url: "{{ _unifi_api }}/rest/networkconf"
        method: GET
        headers:
          x-api-key: "{{ unifi_network_api_key }}"
        validate_certs: false
      register: _all_networks
      check_mode: false
      no_log: "{{ not (debug_no_log | default(false) | bool) }}"

    - name: Find test VLAN network _id
      ansible.builtin.set_fact:
        _test_vlan_net_id: >-
          {{ (_all_networks.json.data
             | selectattr('vlan', 'defined')
             | selectattr('vlan', 'equalto', vault_test_vlan_id | int)
             | list | first | default({})).get('_id', '') }}

    - name: Assert VLAN network exists and is not excluded from port profile
      ansible.builtin.assert:
        that:
          - _test_vlan_net_id | length > 0
          - _test_vlan_net_id not in (_pve_profile.excluded_networkconf_ids | default([]))
        fail_msg: >-
          VLAN {{ vault_test_vlan_id }} is not tagged on port profile '{{ vault_pve_port_profile_name }}'.
          Add it manually in Unifi UI first:
            Settings → Profiles → Port Profiles → {{ vault_pve_port_profile_name }}
            → Tagged Networks → add test-isolation (VLAN {{ vault_test_vlan_id }})
          Then re-run this playbook.

    # ═══════════════════════════════════════════════════════════
    # STEP 1 — Create test-isolation VLAN network (if missing)
    # ═══════════════════════════════════════════════════════════
    - name: Check if test-isolation VLAN already exists
      ansible.builtin.set_fact:
        _test_vlan_exists: >-
          {{ _all_networks.json.data
             | selectattr('vlan', 'defined')
             | selectattr('vlan', 'equalto', vault_test_vlan_id | int)
             | list | length > 0 }}

    - name: Create test-isolation VLAN network
      ansible.builtin.uri:
        url: "{{ _unifi_api }}/rest/networkconf"
        method: POST
        headers:
          x-api-key: "{{ unifi_network_api_key }}"
        body_format: json
        body:
          name: "test-isolation"
          purpose: "corporate"
          vlan: "{{ vault_test_vlan_id | int }}"
          vlan_enabled: true
          ip_subnet: "{{ vault_test_vlan_gateway }}/24"
          dhcpd_enabled: false
          ipv6_interface_type: "none"
        validate_certs: false
        status_code: [200, 201]
      when: not _test_vlan_exists and not ansible_check_mode
      no_log: "{{ not (debug_no_log | default(false) | bool) }}"
      register: _create_vlan

    - name: Record VLAN status
      ansible.builtin.set_fact:
        _vlan_status: "{{ 'created' if not _test_vlan_exists else 'already existed' }}"

    # ═══════════════════════════════════════════════════════════
    # STEP 2a — Resolve zone IDs (zone-based mode only)
    # ═══════════════════════════════════════════════════════════
    - name: Get Unifi firewall zones (v2 API)
      ansible.builtin.uri:
        url: "https://{{ inventory_hostname }}/proxy/network/v2/api/site/default/firewall/zones"
        method: GET
        headers:
          x-api-key: "{{ unifi_network_api_key }}"
        validate_certs: false
      register: _firewall_zones
      check_mode: false
      failed_when: false
      no_log: "{{ not (debug_no_log | default(false) | bool) }}"
      when: use_zone_rules | bool

    - name: Warn if zone API unavailable — will fall back to address-based rules
      ansible.builtin.debug:
        msg: >-
          WARNING: Zone API returned {{ _firewall_zones.status | default('no response') }} —
          falling back to address-based firewall rules.
          (use_zone_rules=true but zone API unavailable; requires Unifi Network 8.2+.)
      when:
        - use_zone_rules | bool
        - _firewall_zones.status | default(0) != 200

    - name: Resolve zone IDs and set effective rule mode
      ansible.builtin.set_fact:
        _effective_zone_rules: "{{ (use_zone_rules | bool) and (_firewall_zones.status | default(0) == 200) }}"
        _semaphore_zone_id: >-
          {{ (((_firewall_zones.json.data
               if (_firewall_zones.json is mapping and 'data' in (_firewall_zones.json | default({})))
               else (_firewall_zones.json | default([]))))
             | selectattr('name', 'equalto', _semaphore_zone_name)
             | list | first | default({})).get('_id', '') }}
        _test_vlan_zone_id: >-
          {{ (((_firewall_zones.json.data
               if (_firewall_zones.json is mapping and 'data' in (_firewall_zones.json | default({})))
               else (_firewall_zones.json | default([]))))
             | selectattr('name', 'equalto', _test_vlan_zone_name)
             | list | first | default({})).get('_id', '') }}

    - name: Assert zone IDs resolved
      ansible.builtin.assert:
        that:
          - _semaphore_zone_id | length > 0
          - _test_vlan_zone_id | length > 0
        fail_msg: >-
          Zone fetch succeeded but could not resolve zone IDs.
          Expected zones: '{{ _semaphore_zone_name }}' and '{{ _test_vlan_zone_name }}'.
          Check _semaphore_zone_name and _test_vlan_zone_name match zone names exactly in Unifi UI
          (Settings → Firewall & Security → Zones).
      when: _effective_zone_rules | bool

    # ═══════════════════════════════════════════════════════════
    # STEP 2b — Firewall rules (manual — zone-based API not accessible)
    # NOTE: The classic /rest/firewallrule POST endpoint rejects all rule_index
    # values when Unifi Network is in zone-based firewall mode (GET returns empty,
    # POST returns FirewallRuleIndexOutOfRange for any 2xxx/4xxx index).
    # Rules must be created manually in the Unifi UI.
    # ═══════════════════════════════════════════════════════════
    - name: Print firewall rule manual creation instructions
      ansible.builtin.debug:
        msg:
          - "═══ MANUAL ACTION REQUIRED — Firewall Rules ═══"
          - "The Unifi zone-based firewall API blocks classic rule creation."
          - "Create these two rules in Unifi UI: Settings → Firewall & Security → Rules → + Add Rule"
          - ""
          - "Rule 1 — '{{ _ssh_rule_name }}'"
          - "  Ruleset: LAN_IN  |  Action: Accept  |  Protocol: TCP"
          - "  Source: {{ _semaphore_ip }}/32"
          - "  Destination: {{ vault_test_vlan_subnet }}  |  Port: 22"
          - "  (Allows Semaphore to SSH into test VMs)"
          - ""
          - "Rule 2 — '{{ _block_rule_name }}'"
          - "  Ruleset: LAN_IN  |  Action: Drop  |  Protocol: All"
          - "  Source: {{ vault_test_vlan_subnet }}"
          - "  Destination: {{ _prod_lan_subnet }}"
          - "  (Blocks test VMs from reaching production LAN)"
          - ""
          - "After creating both rules, re-run this playbook to verify."
      when: not ansible_check_mode

    # ═══════════════════════════════════════════════════════════
    # CHECK MODE — Report
    # ═══════════════════════════════════════════════════════════
    - name: "[CHECK MODE] Report"
      ansible.builtin.debug:
        msg:
          - "=== CHECK MODE — No changes made ==="
          - "VLAN {{ vault_test_vlan_id }} (test-isolation): {{ 'would be created' if not _test_vlan_exists else 'already exists — no action needed' }}"
          - ""
          - "Firewall rules require manual creation in Unifi UI:"
          - "  Rule 1 — '{{ _ssh_rule_name }}': LAN_IN accept TCP {{ _semaphore_ip }}/32 → {{ vault_test_vlan_subnet }}:22"
          - "  Rule 2 — '{{ _block_rule_name }}': LAN_IN drop all {{ vault_test_vlan_subnet }} → {{ _prod_lan_subnet }}"
          - ""
          - "Re-run without --check after creating rules to verify."
      when: ansible_check_mode

    # ═══════════════════════════════════════════════════════════
    # STEP 3 — Verify VLAN exists; check if rules were manually created
    # ═══════════════════════════════════════════════════════════
    - name: Re-fetch networks for verification
      ansible.builtin.uri:
        url: "{{ _unifi_api }}/rest/networkconf"
        method: GET
        headers:
          x-api-key: "{{ unifi_network_api_key }}"
        validate_certs: false
      register: _verify_networks
      no_log: "{{ not (debug_no_log | default(false) | bool) }}"
      when: not ansible_check_mode

    - name: Assert test-isolation VLAN exists
      ansible.builtin.assert:
        that: >-
          _verify_networks.json.data
          | selectattr('vlan', 'defined')
          | selectattr('vlan', 'equalto', vault_test_vlan_id | int)
          | list | length > 0
        fail_msg: "test-isolation VLAN {{ vault_test_vlan_id }} not found"
      when: not ansible_check_mode

    - name: Print summary
      ansible.builtin.debug:
        msg:
          - "=== Test Network Setup — VLAN Complete, Rules Pending ==="
          - "VLAN {{ vault_test_vlan_id }} (test-isolation): {{ _vlan_status }}"
          - ""
          - "⚠ Firewall rules must be created manually (see instructions above)."
          - "  After creating both rules in Unifi UI, re-run to verify the VLAN is still present."
          - ""
          - "Next steps after manual rule creation:"
          - "  1. Run build_ubuntu.yaml -e vm_name=test-vm to provision a test VM"
          - "  2. Verify: VLAN tag on net0 in Proxmox UI, IP in {{ vault_test_vlan_subnet }}"
          - "  3. From test VM: ping prod host → timeout; curl https://hub.docker.com → 200"
      when: not ansible_check_mode
