---
# Verify CephFS appdata mount on a target VM.
# Checks /opt is mounted from CephFS, writes a marker file, reads it back.
# Used to verify bootstrap_vm.yaml and migrate_appdata_to_cephfs.yaml.
#
# Portability proof: run before VM destroy, then again after reprovision —
# marker file persists on CephFS through the rebuild.
#
# Required extra vars:
#   vm_name  — key in vm_definitions (must have cephfs_host_dir defined)

# ═══════════════════════════════════════════════════════════════════
# Play 1 — Resolve target VM
# ═══════════════════════════════════════════════════════════════════
- name: Resolve CephFS verification target
  hosts: localhost
  gather_facts: true
  gather_subset: ['!all', 'date_time']
  vars_files:
    - vars/secrets.yaml
    - vars/vm_definitions.yaml
    - vars/semaphore_check.yaml

  pre_tasks:
    - name: Assert vm_name is defined and has cephfs_host_dir
      ansible.builtin.assert:
        that:
          - vm_name is defined
          - vm_name in vm_definitions
          - vm_definitions[vm_name].cephfs_host_dir is defined
        fail_msg: >-
          vm_name={{ vm_name | default('(unset)') }} is not defined or has no cephfs_host_dir.
          Valid values: {{ vm_definitions | dict2items | selectattr('value.cephfs_host_dir', 'defined') | map(attribute='key') | list | join(', ') }}

    - name: Assert MariaDB logging database is reachable
      include_tasks: tasks/assert_db_connectivity.yaml

    - name: Log playbook run context to MariaDB
      include_tasks: tasks/log_run_context.yaml
      vars:
        log_playbook: "verify_cephfs.yaml"
        log_hostname: "{{ controller_fqdn }}"
        log_run_vars: "{{ {'vm_name': vm_name} | to_json | to_json }}"

  tasks:
    - name: Resolve target parameters
      ansible.builtin.set_fact:
        _cephfs_hostname: "{{ vm_definitions[vm_name].vm_hostname }}"
        _cephfs_host_dir: "{{ vm_definitions[vm_name].cephfs_host_dir }}"
        _cephfs_ip: "{{ vm_definitions[vm_name].vm_ip }}"

    - name: Add target to dynamic inventory
      ansible.builtin.add_host:
        name: "{{ _cephfs_hostname }}"
        ansible_host: "{{ vm_definitions[vm_name].vm_ip }}"
        groups: [cephfs_verify_target]

# ═══════════════════════════════════════════════════════════════════
# Play 2 — Verify CephFS on target VM
# ═══════════════════════════════════════════════════════════════════
- name: Verify CephFS mount
  hosts: cephfs_verify_target
  become: true
  gather_facts: true
  gather_subset: ['!all', 'date_time']
  vars_files:
    - vars/secrets.yaml
    - vars/semaphore_check.yaml

  tasks:
    - name: Initialize verify state
      ansible.builtin.set_fact:
        _verify_failed: false
        _verify_detail: ""

    - block:
        # ─── Mount check ────────────────────────────────────────────
        - name: Check /opt is mounted as CephFS
          ansible.builtin.command: findmnt -t ceph /opt
          register: _findmnt
          changed_when: false

        - name: Show mount info
          ansible.builtin.debug:
            msg: "{{ _findmnt.stdout_lines }}"

        - name: Verify mount source contains expected host dir
          ansible.builtin.assert:
            that: hostvars['localhost']._cephfs_host_dir in _findmnt.stdout
            fail_msg: >-
              /opt is mounted as ceph but source does not contain
              '{{ hostvars['localhost']._cephfs_host_dir }}' — check mount config

        # ─── Read/write check ────────────────────────────────────────
        - name: Write CephFS marker file
          ansible.builtin.copy:
            content: "cephfs-verify {{ ansible_date_time.iso8601 }}\n"
            dest: /opt/.cephfs-verify
            mode: "0644"

        - name: Read marker file back
          ansible.builtin.slurp:
            src: /opt/.cephfs-verify
          register: _marker

        - name: Assert marker file is readable
          ansible.builtin.assert:
            that: "'cephfs-verify' in (_marker.content | b64decode)"
            fail_msg: "Marker file not readable — CephFS read/write may be broken"

        # ─── Informational checks ────────────────────────────────────
        - name: Check /opt/stacks exists
          ansible.builtin.stat:
            path: /opt/stacks
          register: _stacks_dir

        - name: Record verify detail
          ansible.builtin.set_fact:
            _verify_detail: >-
              /opt mounted from CephFS:/{{ hostvars['localhost']._cephfs_host_dir }} —
              marker written and verified —
              {{ '/opt/stacks present' if _stacks_dir.stat.exists else '/opt/stacks not yet deployed' }}

      rescue:
        - name: Set verify failed flag
          ansible.builtin.set_fact:
            _verify_failed: true
            _verify_detail: "{{ ansible_failed_result.msg | default('check Semaphore logs') }}"

# ═══════════════════════════════════════════════════════════════════
# Play 3 — Log to MariaDB and send Discord notification
# ═══════════════════════════════════════════════════════════════════
- name: Log and notify verification result
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
    - vars/semaphore_check.yaml

  tasks:
    - name: Resolve result from target host
      ansible.builtin.set_fact:
        _vf: "{{ hostvars[_cephfs_hostname]._verify_failed | default(true) }}"
        _vd: "{{ hostvars[_cephfs_hostname]._verify_detail | default('Play 2 did not run') }}"

    - name: Log to MariaDB
      include_tasks: tasks/log_mariadb.yaml
      vars:
        log_table: maintenance
        log_application: "{{ vm_name }}"
        log_hostname: "{{ controller_fqdn }}"
        log_type: "Servers"
        log_subtype: "CephFS Verify"
        log_status: "{{ 'failed' if _vf | bool else 'success' }}"

    - block:
        - name: Send Discord notification
          include_tasks: tasks/notify.yaml
          vars:
            discord_name: "CephFS Verify"
            discord_operation: "Verify"
            discord_status: "{{ 'failed' if _vf | bool else 'successful' }}"
            discord_color: "{{ discord_color_failure if _vf | bool else discord_color_success }}"
            discord_url: "{{ semaphore_ext_url }}"
            discord_author: "{{ controller_fqdn }}"
            discord_fields:
              - name: "VM"
                value: "{{ vm_name }}"
                inline: true
              - name: "CephFS Dir"
                value: "{{ _cephfs_host_dir }}"
                inline: true
              - name: "Detail"
                value: "{{ _vd }}"
      rescue:
        - ansible.builtin.fail:
            msg: "Discord notification failed. Re-run with -e debug_no_log=yes for details."

    - name: Fail play if verification failed
      ansible.builtin.fail:
        msg: "CephFS verification failed: {{ _vd }}"
      when: _vf | bool
