---
# Lightweight test VLAN isolation verification.
# Provisions a bare test VM (no stacks, no restore, no VIPs), runs network
# isolation checks, then destroys the VM.
#
# Proves the Unifi "Block Test to Internal" zone policy prevents test VMs
# from reaching production hosts (gateway, PVE, DNS) while allowing CephFS
# and public internet.
#
# Usage:
#   ansible-playbook verify_isolation.yaml -e vm_name=cephfs-migrate-test
#   ansible-playbook verify_isolation.yaml -e vm_name=test-vm
#
# Required extra vars:
#   vm_name — test VM key from vm_definitions (cephfs-migrate-test or test-vm)

# ═══════════════════════════════════════════════════════════════════
# Play 1 — Provision test VM
# ═══════════════════════════════════════════════════════════════════
- name: Provision test VM for isolation check
  hosts: localhost
  gather_facts: true
  gather_subset: ['!all', 'date_time']
  vars_files:
    - vars/secrets.yaml
    - vars/proxmox.yaml
    - vars/vm_definitions.yaml
    - vars/semaphore_check.yaml

  pre_tasks:
    - name: Run standard pre-flight assertions
      ansible.builtin.include_tasks: tasks/pre_task_assertions.yaml
      vars:
        pre_playbook: "verify_isolation.yaml"
        pre_hostname: "{{ controller_fqdn }}"
        pre_run_vars: "{{ {'vm_name': vm_name | default('undefined')} | to_json }}"

    - name: Assert vm_name exists in vm_definitions
      ansible.builtin.assert:
        that:
          - vm_name is defined
          - vm_name in vm_definitions
        fail_msg: >-
          vm_name '{{ vm_name | default('undefined') }}' not found in vm_definitions.
          Valid test VMs: test-vm, cephfs-migrate-test

    - name: Assert VM is a test VM (VLAN-tagged)
      ansible.builtin.assert:
        that:
          - vm_definitions[vm_name].vm_vlan_tag is defined
        fail_msg: >-
          vm_name '{{ vm_name }}' is not a VLAN-tagged test VM.
          This playbook only runs on isolated test VMs.

  tasks:
    - name: Auto-detect free vm_index for test-vm pool
      include_tasks: tasks/resolve_test_vm_index.yaml
      when: vm_name in ['test-vm', 'cephfs-migrate-test']

    - name: Resolve VM definition
      ansible.builtin.set_fact:
        _vm: "{{ vm_definitions[vm_name] }}"

    # ===== AUTO-CREATE CEPHFS DIR (when vm has cephfs_host_dir) =====
    - name: Add PVE host to in-memory inventory (for CephFS dir creation)
      ansible.builtin.add_host:
        name: pve_builder
        ansible_host: "{{ pve_api_host }}"
        ansible_user: ansible
      when: _vm.cephfs_host_dir is defined

    - name: Ensure test VM CephFS directory exists (isolated from production)
      ansible.builtin.shell: |
        set -e
        MOUNT_DIR=$(mktemp -d)
        ADMIN_KEY=$(ceph auth print-key client.admin)
        mount -t ceph {{ vault_ceph_mons }}:/ "$MOUNT_DIR" \
          -o "name=admin,secret=${ADMIN_KEY}"
        if [ -d "$MOUNT_DIR/{{ _vm.cephfs_host_dir }}" ]; then
          echo "exists"
        else
          mkdir "$MOUNT_DIR/{{ _vm.cephfs_host_dir }}"
          echo "created"
        fi
        umount "$MOUNT_DIR"
        rmdir "$MOUNT_DIR"
      args:
        executable: /bin/bash
      delegate_to: pve_builder
      become: true
      register: _cephfs_dir_result
      changed_when: "'created' in _cephfs_dir_result.stdout"
      no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"
      when: _vm.cephfs_host_dir is defined

    # ===== RESOLVE OR PROVISION VM =====
    - name: Resolve or provision test VM
      include_tasks: tasks/resolve_or_provision_vm.yaml
      vars:
        _provision_target_group: test_target

# ═══════════════════════════════════════════════════════════════════
# Play 2 — Bootstrap (minimal — no stacks, no VIPs)
# ═══════════════════════════════════════════════════════════════════
- name: Bootstrap test VM
  hosts: test_target
  become: true
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
    - vars/vm_definitions.yaml
    - vars/docker_vips.yaml

  tasks:
    - name: Wait for system boot to complete
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 300

    - name: Gather facts
      ansible.builtin.setup:

    # No role injection — no keepalived, no VIPs

    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: _docker_check
      failed_when: false
      changed_when: false
      become: false

    - name: Bootstrap Ubuntu with Docker and security hardening
      include_tasks: tasks/bootstrap_vm.yaml
      vars:
        _vm: "{{ hostvars['localhost']._vm }}"
      when: hostvars[inventory_hostname]._needs_bootstrap | default(false) or _docker_check.rc != 0

# ═══════════════════════════════════════════════════════════════════
# Play 3 — Run isolation checks
# ═══════════════════════════════════════════════════════════════════
- name: Verify network isolation
  hosts: test_target
  become: true
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
    - vars/vm_definitions.yaml
    - vars/docker_vips.yaml

  tasks:
    - name: Initialize verify state
      ansible.builtin.set_fact:
        _verify_failed: false
        _verify_detail: ""

    - block:
        - name: Assert /opt is not production CephFS (safety gate)
          include_tasks: tasks/assert_test_vm.yaml

        - name: Verify test VLAN isolation from production
          include_tasks: tasks/verify_network_isolation.yaml
          vars:
            _vm: "{{ hostvars['localhost']._vm }}"

        - name: Record verify detail
          ansible.builtin.set_fact:
            _verify_detail: "{{ _network_isolation_summary }}"

        - name: Display summary
          ansible.builtin.debug:
            msg: "Network isolation: {{ _network_isolation_summary }}"

      rescue:
        - name: Set verify failed flag
          ansible.builtin.set_fact:
            _verify_failed: true
            _verify_detail: "{{ ansible_failed_result.msg | default('check Semaphore logs') }}"

# ═══════════════════════════════════════════════════════════════════
# Play 4 — Destroy test VM
# ═══════════════════════════════════════════════════════════════════
- name: Destroy test VM
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
    - vars/vm_definitions.yaml

  tasks:
    - name: Stop VM
      community.general.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
        node: "{{ _vm_actual_node }}"
        vmid: "{{ vm_definitions[vm_name].vm_id }}"
        state: stopped
        force: true
      no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"
      ignore_errors: true

    - name: Wait for VM to stop
      ansible.builtin.pause:
        seconds: 10

    - name: Delete VM
      community.general.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
        node: "{{ _vm_actual_node }}"
        vmid: "{{ vm_definitions[vm_name].vm_id }}"
        state: absent
      no_log: "{{ not (debug_no_log | default(false) | bool) and (ansible_verbosity | default(0) | int < 3) }}"

# ═══════════════════════════════════════════════════════════════════
# Play 5 — Log to MariaDB and send Discord notification
# ═══════════════════════════════════════════════════════════════════
- name: Log and notify verification result
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/secrets.yaml
    - vars/semaphore_check.yaml

  tasks:
    - name: Resolve result from target host
      ansible.builtin.set_fact:
        _vf: "{{ hostvars[groups['test_target'][0]]._verify_failed | default(true) }}"
        _vd: "{{ hostvars[groups['test_target'][0]]._verify_detail | default('Play 3 did not run') }}"

    - name: Log verification result to MariaDB
      ansible.builtin.include_tasks: tasks/log_mariadb.yaml
      vars:
        log_table: maintenance
        log_application: "Test Isolation"
        log_hostname: "{{ controller_fqdn }}"
        log_type: "Local"
        log_subtype: "Verify"
        log_status: "{{ 'failed' if (_vf | bool) else 'success' }}"
      when: not ansible_check_mode

    - name: Send alert on failure
      ansible.builtin.include_tasks: tasks/notify.yaml
      vars:
        discord_name: "Test Isolation"
        discord_operation: "Verification"
        discord_status: "failed"
        discord_detail: "{{ _vd }}"
        discord_color: "{{ discord_color_failure }}"
        discord_author: "{{ controller_fqdn }}"
        discord_fields:
          - name: "VM"
            value: "{{ vm_name }}"
            inline: true
          - name: "Detail"
            value: "{{ _vd }}"
            inline: false
      when: _vf | bool

    - name: Fail play if verification failed
      ansible.builtin.fail:
        msg: "Network isolation verification failed: {{ _vd }}"
      when: _vf | bool
